#!/usr/bin/env perl
use Text::Autoformat qw(autoformat break_wrap);

$default = { right => 72, squeeze => 1, all => 0, break=>break_wrap };
$input = '$user = {' . $ARGV[0] . '};';
eval $input;
%$user = () if $@;

$out = autoformat { %$default, %$user };

# standardize trailing newline behavior, e.g. strip it.
chomp $out;
print $out;
