#!/bin/sh
#
# dmanview - copy and preview a man page (while writing it install it
# and review that the docs look good)

FILE=${1?Usage: dmanview manfile}

set -e

SECTION=`fdsplit ext "$FILE"`
[ -z "$SECTION" ] && {
   echo >&2 "no section extension in '$FILE'"
   exit 65
}

[ ! -d "$HOME/usr/share/man/man$SECTION" ] && {
   echo >&2 "notice: mkdir $HOME/usr/share/man/man$SECTION"
   sleep 1
   mkdir -p -- "$HOME/usr/share/man/man$SECTION"
}
cp -p -- "$FILE" "$HOME/usr/share/man/man$SECTION/`basename $FILE`"

PAGE=`fdsplit root "$FILE"`
PAGE=`basename "$PAGE"`

exec man -- "$SECTION" "$PAGE"
