#!/bin/sh
#
# Reverses command line arguments, for when the .foo longer name needs
# to come first, e.g. when doing stuff like:
#
# diff annoying-long-name.orig annoying-long-name
#
# becomes:
#
# diff `esr annoying*`
#
# or:
#
# esr annoying* | xargs diff

for x in "$@"; do
  out="$x $out"
done

echo $out
