.Dd October  6, 2016
.Dt FEED 1
.nh
.Os
.Sh NAME
.Nm feed
.Nd feeds commands into a REPL
.Sh SYNOPSIS
.Nm feed
.Ar inputfile|-
.Ar command
.Op Ar command-args ..
.Ek
.Sh DESCRIPTION
.Nm
reads commands from the given
.Pa inputfile
or standard input if
.Ar -
is given as the filename, and feeds these commands to the subsequent
command, ideally some sort of REPL. Once the commands have been fed, the
user will be able to interact with the REPL manually.
.Pp
Support for a REPL must be written into the code; see the code
for details.
.Sh EXIT STATUS
.Nm
will turn execution over to the
.Ar command
though remains running during that exection.
.Sh EXAMPLES
From a 
.Xr vi 1
buffer containing LISP code, one could issue
.Pp
.Dl Ic :!feed % clisp -q -q
.Pp
to feed the contents of the buffer to clisp. Standard input is also
supported as a source of input:
.Pp
.Dl $ Ic echo run -al | feed - gdb ls
.Pp
.Sh SEE ALSO
.Xr expect 1
.Sh AUTHOR
.An Jeremy Mates
