.Dd September 10 2019
.Dt FEED 1
.nh
.Os
.Sh NAME
.Nm feed
.Nd feeds commands into a REPL
.Sh SYNOPSIS
.Bk -words
.Nm
.Ar file|-
.Ar command
.Op Ar args ..
.Ek
.Sh DESCRIPTION
.Nm
reads lines from the given
.Pa file
(or stdin) and feeds those lines to the subsequent
.Ar command ,
Once all the lines have been fed the user will be able to
.Ic interact
with the REPL manually.
.Pp
Support for a REPL should ideally be written into
.Pa ~/.feedrc .
See the code for the default behavior.
.Pp
Input of
.Ic control+z
will cause
.Nm
(and the
.Ar command )
to stop. A
.Ic control+c
will be relayed from
.Nm
to the 
.Ar command .
Try
.Ic control+\e
if things go horribly awry.
.Sh ENVIRONMENT
.Ev FEEDRC
allows the path to the
.Pa ~/.feedrc
file to be customized.
.Sh FILES
The file
.Pa ~/.feedrc
must exist, and should contain TCL code that customized how lines are
parsed and fed to a REPL.
.Sh EXIT STATUS
.Ex -std
.Pp
However, the exit status once
.Nm
has begun to
.Ic interact
with the given
.Ar command
will likely always be 0 (regardless how the
.Ar command
exits), unless a
.Dv HUP ,
.Dv PIPE ,
or
.Dv TERM
signal is sent.
.Sh EXAMPLES
From a
.Xr vi 1
buffer containing LISP code in a file, one could issue
.Pp
.Dl Ic :!feed % sbcl --noinform
.Pp
to feed the data to
.Pa sbcl .
Standard input can also be used;
.Pp
.Dl $ Ic echo run -al \&| feed - gdb -q ls
.Pp
would run
.Pa ls
under
.Pa gdb
and then launch
.Pa ls
with the arguments
.Ar -al 
and then turn
.Pa gdb
over to the user. From an editor, one may use a
.Pa fooprog.gdb
file containing whatever GDB commands are necessary, e.g.
.Pp
.Dl shell make fooprog
.Dl file ./fooprog
.Dl set args some args to fooprog
.Dl break somecall
.Dl commands
.Dl silent
.Dl watch somevarinsomecall
.Dl continue
.Dl end
.Dl run
.Pp
and then set your editor to feed this to
.Nm .
A
.Xr vim 1
mapping might look something like:
.Pp
.Dl map <Leader>t :!feed % egdb -q<CR><CR>
.Sh SEE ALSO
.Xr entr 1 ,
.Xr expect 1 ,
.Xr vi 1 ,
.Xr zcomppoke 1
.Sh AUTHOR
.An Jeremy Mates
.Sh CAVEATS
History functionality for a REPL may need to be disabled
because repeated
.Nm
runs will spam the history with repeated entries.
