copycat: copycat.c
muss-with-environ: muss-with-environ.c
setsid: setsid.c
threading: threading.c
timeout: timeout.c

clean:
	@-rm -f copycat muss-with-environ setsid threading timeout *.core 2>/dev/null
