.Dd November 20 2017
.Dt MUSS-WITH-ENVIRON 1
.nh
.Os
.Sh NAME
.Nm muss-with-environ
.Nd adds duplicate environment variables to environment
.Sh SYNOPSIS
.Nm muss-with-environ
.Ar command
.Op Ar args ..
.Ek
.Sh DESCRIPTION
.Nm
adds duplicate environment variables to the environment (these are hard
coded, adjust the source code or see
.Xr dupenv
for something more dynamic) then runs the given
.Ar command .
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
.Dl $ Ic muss-with-environ env | grep FOO=
.Dl FOO=bar
.Dl FOO=zot
.Dl $ 
.Pp
.Sh SEE ALSO
.Xr dupenv 1 ,
.Xr environ 7 ,
.Xr execve 2 ,
.Xr nodupenv 1 ,
.Xr Proc::FastSpawn 3pm
.Sh AUTHOR
.An Jeremy Mates
