#!/bin/sh
#
# not-ascii - converts a-zA-Z to Unicode ranges that are "not ASCII"
#
# see "Studies in Words" by C.S. Lewis to understand the drift of the
# very specific term ASCII to mean "anything textish, as opposed to
# not-textual graphics" in casual conversation, for example:
#
# "but not a good looking ascii roguelike (like cogmind, or brogue)"
#
# except Brogue uses Unicode, and not ASCII

printf "%s\n" "$*" | ntr 97,122:65248 65,90:65248
