#!/usr/bin/env zsh
#
# If PDF already open (according to a simple ps search), send reader HUP.
# Otherwise, open document. For use on OpenBSD, as Mac OS X has a different
# open(1) that like this I mostly use for opening PDF files.

PDFREADER=mupdf

File=$1

if [[ ! -r $File ]]; then
  echo >&2 `basename $0`: could not read $File
  exit 1
fi

ps xo pid,command | while read pid cmd cmdargs; do
  if [[ $cmd = $PDFREADER ]]; then
    if [[ $cmdargs =~ $File ]]; then
      kill -HUP $pid
      exit 0
    fi
  fi
done

setsid $PDFREADER -- "$File" 1>>~/var/log/pdf 2>&1 &|
