.Dd July 7, 2014
.Dt TIMEOUT 1
.nh
.Os
.Sh NAME
.Nm timeout
.Nd terminates a command after the specified amount of time
.Sh SYNOPSIS
.Nm timeout
.Bk -words
.Op Fl q
.Ar duration
.Ar command
.Op Ar command-args ...
.Ek
.Sh DESCRIPTION
.Nm
sends SIGTERM to the specified command if it does not exit within the specified duration.
.Fl q
makes
.Nm
emit less noise.
.Pp
.Sh EXAMPLES
.Dl timeout 3 sleep 7
.Dl timeout 3m21s sleep 202
.Sh EXIT STATUS
.Ex -std timeout
.Sh SEE ALSO
.Xr timeout 1
.Pp
Linux apparently has a related
.Nm
utility, but I am hardly ever on that, and only became aware of it well after writing the original Perl program.
.Sh AUTHOR
.An Jeremy Mates
