#!/usr/bin/env perl
#
# Twiddles case.

use Getopt::Std;
my %opts;
getopts('ul', \%opts);

END {
  # Report problems when writing to stdout (perldoc perlopentut)
  unless ( close(STDOUT) ) {
    warn "error: problem closing STDOUT: $!\n";
    exit 74;
  }
}

chomp(@ARGV = <STDIN>) unless @ARGV;

for (@ARGV) {
  print $opts{l} ? lc : uc;
  print "\n";
}
