.Dd August 16 2019
.Dt WAITORNOT 1
.nh
.Os
.Sh NAME
.Nm waitornot
.Nd waits for a command to complete, or not
.Sh SYNOPSIS
.Bk -words
.Nm
.Op Fl I
.Bk -words
.Ar command 
.Op Ar args ..
.Ek
.Sh DESCRIPTION
.Nm
waits for the given command to complete, or on (almost) any keypress
closes the command (by sending it the TERM signal). This requires that
standard input be attached to a TTY, and consequently that no standard
input can be piped to the
.Ar command ;
to help enforce this, standard input to the
.Ar command
is reopened to
.Pa /dev/null .
.Pp
.Nm
only emits to standard error should there be a problem; standard
output is not used.
.Pp
Options:
.Bl -tag -width Ds
.It Fl I
Disables ISIG such that INTR, QUIT, and others generate no signals; ISIG
is otherwise enabled by default, though the key for SUSP (and DSUSP,
maybe) is disabled by default, so a ^Z (or ^Y, maybe) should cause the
command to exit early, regardless.
.El
.Sh EXIT STATUS
.Ex -std
The exit status of the
.Ar command
will not be passed along; if the child exits, the exit status from
.Nm
will be 0 regardless.
.Sh SEE ALSO
.Xr blocksig 1 ,
.Xr feed 1 ,
.Xr getraw 1 ,
.Xr prte 1 ,
.Xr termios 5
.Sh AUTHOR
.An Jeremy Mates
.Sh CAVEATS
Detection of whether a given OS supports DSUSP is poor, and should
ideally be done with something like
.Cm autoconf .
Use the
.Fl I
option to limit the availability of signal-generating keys, though this
will remove the customary behavior of e.g. control+c.
.Pp
Various terminate-by-default signals will cause
.Nm
to exit and thus perhaps leave the terminal in a somewhat raw state.
This should not be a problem if the TTY is being closed, or the system
shutting down, or if the parent shell is smart enough to restore the
original terminal state.
