#!/bin/sh
#
# yak - unix diagnostic tool that saves various invocation details to a
# temporary file for debugging. other options are to use tool like
# strace or sysdig...

YAK_OUTPUT=`mktemp -q "/tmp/yak.XXXXXXXXXX"` || {
   echo >&2 "mktemp failed to create /tmp file"
   exit 1
}
chmod go-r "$YAK_OUTPUT"
(
   printf "$0 $@\npid=$$\n"
   # NOTE may need to fiddle with this or use other utilities to get the
   # real vs. effective user...
   id
   groups
   printf "\n"
   tty
   printf "\n"
   env
   printf "\n"
   if [ -t 0 ]; then
      printf "istty\n"
   else
      cat
   fi
) >> "$YAK_OUTPUT"
