#!/bin/sh
#
# Generates new host keys for servers running OpenSSH. Some OS include
# scripts to handle this, e.g. via their ports or package systems. The
# known_hosts data on client systems will also need to change, or will
# otherwise show warnings. Regenerating new keys from time to time is
# advisable, especially on low-entropy-at-install-time virts.
#
# Usage:
#   ssh-genhostkeys            (assumes /etc/ssh, otherwise tries /etc)
#   ssh-genhostkeys /some/dir
#
# NOTE Debian may lack `ssh-keygen -A`; try:
#   rm /etc/ssh/ssh_host_*
#   dpkg-reconfigure openssh-server

keydir=/etc/ssh

if [ ! -z "$1" ]; then
  keydir=$1
else
  # Older systems (and still Mac OS X or at least my 10.8 updgraded from
  # 10.6) keep SSH keyfiles under /etc instead of /etc/ssh.
  if [ ! -d "$keydir" ]; then
    keydir=/etc
  fi
fi

if [ ! -d "$keydir" ]; then
  echo "error: no such directory: file=$keydir" >&2
  exit 72
fi

if [ "$keydir" = "/" ]; then
  echo "warning: key directory is root: file=$keydir" >&2
  sleep 3
fi

rm -- "$keydir/"ssh_host_*
ssh-keygen -A || exit 1
for f in "$keydir/"ssh_host_*; do ssh-keygen -l -f $f; done
