.Dd October 12 2016
.Dt DATE2EPOCH 1
.nh
.Os
.Sh NAME
.Nm date2epoch
.Nd convert date to epoch
.Sh SYNOPSIS
.Nm date2epoch
.Op Fl hq
.Op Ar YYYY-MM-DD HH:MM:SS
.Sh DESCRIPTION
The
.Nm
utility attempts to convert a
.Cm YYYY-MM-DD HH:MM:SS
timestamp via
.Xr strptime 3
to epoch time. The day, day and month, seconds, seconds and minutes,
etc. are optional.
.Pp
Options:
.Bl -tag -width Ds
.It Fl h
Print brief usage note.
.It Fl q
Do not print warning if non-UTC timezone detected in third argument
to script.
.El
.Sh EXAMPLES
.Dl $ Ic date2epoch 2003-07-31 17:44:00 UTC
.Dl $ Ic date2epoch 2014 15
.Sh EXIT STATUS
.Ex -std date2epoch
.Sh SEE ALSO
.Xr date 1 ,
.Xr epoch2date 1 ,
.Xr epochal 1
.Sh AUTHOR
.An Jeremy Mates
