.Dd May 20 2017
.Dt EPOCH2DATE 1
.nh
.Os
.Sh NAME
.Nm epoch2date
.Nd formats epoch dates in human readable form 
.Sh SYNOPSIS
.Nm
.Bk -words
.Op Fl f Ar format
.Op Ar epoch-numbers|-
.Ek
.Sh DESCRIPTION
.Nm
converts unix epoch seconds to a human readable form. Will attempt to
guess if the timestamp appears to be in microseconds.
Options:
.Bl -tag -width Ds
.It Fl f Ar format
Format for 
.Xr strftime 3 ;
the default is something ISO-8601ish.
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
.Dl $ Ic epoch2date -f '%Y' `perl -E 'say time'`
.Dl $ Ic (echo 1059673440; echo 1404433529) \&| xargs epoch2date
.Dl $ Ic echo 1059673440 1404433529 \&| epoch2date -
.Pp
If a specific timezone is necessary, set that as appropriate.
.Pp
.Dl $ Ic TZ=US/Pacific epoch2date 1404662217
.Pp
.Dl $ Ic epoch2date 1475682078014325
.Sh SEE ALSO
.Xr date 1 ,
.Xr date2epoch 1 ,
.Xr epochal 1 ,
.Xr strftime 3
.Sh AUTHOR
.An Jeremy Mates
.Sh CAVEATS
Usual portability warnings regarding
.Xr strftime 3
and the Perl implementation thereof in
.Xr POSIX 3pm .
Consult that documentation for more details.
