#!/usr/bin/env perl
use 5.24.0;
use warnings;
use Astro::MoonPhase qw(phasehunt);
use POSIX qw(strftime);
my @prefix = (
    "New Moon      = ",
    "First quarter = ",
    "Full moon     = ",
    "Last quarter  = ",
    "New Moon      = ",
);
my @phases = phasehunt();
my $i      = 0;
my $now    = time();
my $n      = $phases[0] > $now ? 0 : @phases;
my $search = 1;

for my $i ( 0 .. $#phases ) {
    if ( $search and $phases[$i] > $now ) {
        $n      = $i;
        $search = 0;
    }
    $phases[$i] = localtime $phases[$i];
}
splice @prefix, $n, 0, "          now = ";
splice @phases, $n, 0, strftime "%a %b %d %H:%M:%S", localtime $now;
for my $i ( 0 .. $#phases ) {
    say $prefix[$i] . $phases[$i];
}
