#!/bin/sh
#
# Prints the date in a format to the liking of the author (in hindsight, it
# would probably have been more sensible to simply create a `date` alias with
# just the strftime format to that, and none of the options fuss).

DODATE=no
DOTIME=no
DOTIME_ZONE=no
QUERY=

OPT=
while getopts dtz OPT; do
  case $OPT in
    d)
      DODATE=yes
    ;;
    t)
      DOTIME=yes
    ;;
    z)
      DOTIME_ZONE=yes
    ;;
  esac
done
shift `expr $OPTIND - 1`

# for RPM .spec changelog foo, of which thankfully very little I now do
if [ "$1" = "rpm" ]; then
  [ -z "$MY_REALNAME" ] && MY_REALNAME=`whoami`
  [ -z "$MY_EMAIL" ] && MY_EMAIL="`whoami`@`hostname`"
  date "+* %a %b %d %Y $MY_REALNAME <$MY_EMAIL>"
  exit
fi

# form up query specification for date(1) command
if test $DODATE = yes ; then
  QUERY='%Y-%m-%d'
fi
if test $DOTIME = yes ; then
  QUERY="${QUERY:+$QUERY }%H:%M"
fi
if test $DOTIME_ZONE = yes ; then
  QUERY=${QUERY:+$QUERY}%z
fi

date "+$QUERY"
