#!/bin/sh
#
# Prints intials/date in standard format I use when commenting files. Now
# wrapped by a ZSH shell function to copy to the clipboard (which will need to
# vary by OS due to differing clipboard commands):
#
#   function tagit {
#     =tagit -id | pbcopy
#   }

# use username instead of initials, as easier to query these e.g. with
# `getent passwd ...` or the like.
INITIALS=`id -un`@
DATE=`date +%Y-%m-%d`

DOINITIALS=no
DODATE=no
DONEWLINE=no
DOMESSAGE=no
OUTPUT=

tagit () {
  if test $DOINITIALS = yes ; then
    OUTPUT=$INITIALS
    if test $DODATE = yes ; then
      OUTPUT="$OUTPUT "
    fi
  fi
  if test $DODATE = yes ; then
    OUTPUT="${OUTPUT}$DATE"
  fi
}

custommsg () {
  DATA=`cat`
  if echo $DATA | grep '^#' > /dev/null ; then
    echo $DATA | sed "s/^#[ ]*/# $OUTPUT\ /"
  else
    echo $DATA | sed "s/^/$OUTPUT\ /"
  fi
}

OPT=
while getopts vidn OPT; do
  case $OPT in
    i)
      DOINITIALS=yes
    ;;
    d)
      DODATE=yes
    ;;
    n)
      DONEWLINE=yes
    ;;
    v)
      DOMESSAGE=yes
    ;;
  esac
done
shift `expr $OPTIND - 1`

# form up $OUTPUT with date, initials, etc.
tagit

if test $DOMESSAGE = yes ; then
  custommsg
else
  echo $OUTPUT | tr -d '\n'
  if test $DONEWLINE = yes ; then
    echo
  fi
fi
