#!/usr/bin/perl -w
#
# Generates short (eight character) hashes from MD5 hex signatures.
# These are used by OpenSSL in certain cases.
#
# The author disclaims all copyrights and releases this script into the
# public domain.

use strict;

use Digest::MD5;

END {
  # Report problems when writing to stdout (perldoc perlopentut)
  unless ( close(STDOUT) ) {
    die "error: problem closing STDOUT: $!\n";
  }
}

my $fh;

if (@ARGV) {
  my $file = shift;

  open $fh, "< $file" or die "error: could not open $file: $!\n";
  binmode $fh;
} else {
  $fh = *STDIN;
}

printf "%08x\n", unpack "N", Digest::MD5->new->addfile($fh)->digest;

=pod SCRIPT CATEGORIES

Utilities

=cut
