#!/bin/sh
#
# Unix diagnostic tool that saves various invocation details such as arguments,
# environment settings, and standard input to a temporary file for debugging.
# Uses include seeing how and with what settings applications such as the LPRng
# print spooler or the Procmail mail delivery agent call filters or external
# scripts. (Which may date this script's origins to a particular era, though it
# does remain handy for debugging now other things.)
#
# Output is saved to a temporary file under /tmp by default.

shortname=`basename $0`
shortname=${shortname:=yak}

#YAK_OUTPUT=/dev/null
YAK_OUTPUT=`mktemp -q /tmp/${shortname}.XXXXXXXXXX` || {
  echo >&2 "mktemp failed to create /tmp file"
  exit 1
}

# in the event env contains anything sensitive (or change the tmp dir path)
chmod go-r $YAK_OUTPUT

#logger -t $shortname "saving output to $YAK_OUTPUT"

(
if [ $# -gt 0 ]; then
  echo ARGS::BEGIN
  echo $0
  for YAK_ARG in "$@"; do
    echo $YAK_ARG
  done
  echo ARGS::END
else
  echo ARGS::NONE
fi
echo

echo UNIX::BEGIN
echo pid=$$

# NOTE may need to fiddle with this or use other utilities to get the real vs.
# effective user and group settings
id

echo UNIX::END
echo

if test -t 0; then
  echo TTY::BEGIN
  tty
  echo TTY::END
else
  echo TTY:NONE
fi
echo

echo ENV::BEGIN
set
echo ENV::END
echo

# NOTE this will stall the script on command line waiting for input
echo STDIN::BEGIN
cat
echo STDIN::END

) >> $YAK_OUTPUT

exit 0
