#!/bin/sh
#
# CVS_RSH environment variable wrapper script that allows arguments to
# the target binary.

# Require non-interactive authentication methods to prevent things from
# stalling on a password prompt. Also disable agent, X11, other
# forwards.
exec /usr/bin/ssh -a -x \
  -o ClearAllForwardings=yes \
  -o PreferredAuthentications=hostbased,publickey,gssapi-with-mic "$@"
