#!/bin/sh
#
# Somewhat smart "diff" utility, does VCS-appropriate diff if this seems
# relevant (by various file tests), or attempts regular diff. Requires
# `findup`, available elsewhere.

findup -H -q .git && {
    WHAT=
    if [ "$#" -gt 0 ]; then
        WHAT="$@"
    else
        WHAT=.
    fi
    git diff --quiet --exit-code "$WHAT"
    STATUS=$?
    if [ "$STATUS" -eq 1 ]; then
        exec git diff "$WHAT"
    else
        exit "$STATUS"
    fi
}

[ -f CVS/Root ] && exec cvs diff "$@"

if [ "$#" -eq 0 ]; then
    echo >&2 "Usage: di [file1 ..]"
    exit 64
else
    for input in "$@"; do
        if [ ! -f "$input" ]; then
            echo >&2 "di: skipping non-file: '$input'"
            continue
        fi
        # *.orig and *.old common conventions I use for quick edits, *.orig
        # for the orig command
        for backup_suffix in .orig .old; do
            if [ -f "$input$backup_suffix" ]; then
                diff -u -- "$input$backup_suffix" "$input"
                break
            fi
        done
    done
fi
