.Dd November 22 2017
.Dt KETCHUP 1
.nh
.Os
.Sh NAME
.Nm ketchup
.Nd performs version control updates
.Sh SYNOPSIS
.Bk -words
.Nm
.Op Fl f
.Op Ar dir ..
.Ek
.Sh DESCRIPTION
.Nm
performs a context-sensitive "update" as appropriate for the current or
a given directory (for example
.Cm git status
or such).
.Pp
The
.Fl f
flag "forces" matters, for some of the supported version control
softwares. Other behavior may depend on the directory, see the source.
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr cvs 1 ,
.Xr findup 1 ,
.Xr git 1
.Sh AUTHOR
.An Jeremy Mates
.Sh HISTORY
Used to be called 
.Nm up
but that conflicted with a tool from OpenAFS.
