.Dd November 22 2017
.Dt ORIG 1
.nh
.Os
.Sh NAME
.Nm orig
.Nd makes an original of a file
.Sh SYNOPSIS
.Bk -words
.Nm
.Ar
.Ek
.Sh DESCRIPTION
.Nm
copies each filename given to a
.Pa file.orig
backup filename. Consider instead using version control.
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr di 1 ,
.Xr diff 1
.Sh AUTHOR
.An Jeremy Mates
