#!/bin/sh
#
# Creates original copies of the specified file(s). Instead use version
# control, sheesh!

if [ "$#" -eq 0 ]; then
    echo >&2 "Usage: orig file [file1 ..]"
    exit 64
fi

STATUS=0

for f in "$@"; do
    if [ ! -r "$f" ]; then
        echo >&1 "orig: cannot read file '$f'"
        STATUS=1
    elif [ -f "$f" ]; then
        cp -p -f -- "$f" "$f.orig"
        STATUS=$?
    else
        echo >&2 "orig: no method to handle '$f'"
        STATUS=1
    fi
done

exit "$STATUS"
