#!/bin/sh
#
# Expands source RPMs via rpm2cpio(8) and cpio(1) into a RedHat build
# directory area, by default the system-wide /usr/src/redhat. To use a
# custom build area, consult the "Maximum RPM" documentation online for
# instructions on creating a ~/.rpmmacros file and the required
# directory structure.

RPM_MACROS=$HOME/.rpmmacros
RPM_TOPDIR=/usr/src/redhat

# exit code is set to a non-zero value if there are problems running
# something, so will see the exit status of the last utility to fail
STATUS=0

if [ -z "$1" ]; then
  echo "Usage: `basename $0` srcrpm [srcrpm2 ...]" >&2
  exit 64
fi

if [ -f $RPM_MACROS ]; then
  RPM_TOPDIR=`awk '{if ( $1 == "%_topdir" ) print $2}' $RPM_MACROS`
  if [ ! -d $RPM_TOPDIR ]; then
    echo "error: RPM _topdir not a directory: $RPM_TOPDIR" >&2
    exit 1
  fi
fi

RPM_SOURCES=$RPM_TOPDIR/SOURCES
if [ ! -d $RPM_SOURCES ]; then
  echo "error: no SOURCES directory under RPM _topdir: $RPM_TOPDIR" >&2
  exit 1
fi

RPM_SPECS=$RPM_TOPDIR/SPECS
if [ ! -d $RPM_SPECS ]; then
  echo "error: no SPECS directory under RPM _topdir: $RPM_TOPDIR" >&2
  exit 1
fi

for file in "$@" ; do
  if [ ! -f $file ]; then
    echo "notice: skipping non-existent argument: $file" >&2
    STATUS=1
    continue
  fi

  rpm2cpio $file | ( cd $RPM_SOURCES && cpio -id 2>/dev/null )
  if [ $? -ne 0 ]; then
    STATUS=$?
    echo "warning: non-zero exit ($STATUS) when unpacking: $file" >&2
  fi
done

mv $RPM_SOURCES/*.spec $RPM_SPECS
if [ $? -ne 0 ]; then
  STATUS=$?
fi

exit $STATUS
