#!/usr/bin/perl -w
#
# $Id$
#
# The author disclaims all copyrights and releases this script into the
# public domain.
#
# Prints path information about specified file paths with optional
# warnings about particular user or group problems with specified paths.

use strict;
use File::Spec;

sub getfileinfo;

# unix file type mappings
# TODO use "use Fcntl ':mode';" instead?
my %filetype = (
  '0010000' => 'p',
  '0020000' => 'c',
  '0040000' => 'd',
  '0060000' => 'b',
  '0100000' => 'f',
  '0120000' => 'l',
  '0140000' => 's',
  '0160000' => 'w',
);

my %opts;
for (@ARGV) {
  # TODO make this a dispatch table?
  if (/^\+([rwx]+)$/) {
    my $perms = $1;
    for ($perms =~ /(.)/g) { $opts{perms}->{$_} = 1 }
  } elsif (/^(user|group)=(.+)$/) {
    my $what = $1;
    my $who  = $2;

    # TODO resolve user/group -> id, warn if not on system, etc.

    $opts{$what} = $who;
  } elsif (/^-([\w]+)$/) {
    my $opts = $1;
    for ($opts =~ /(.)/g) { $opts{options}->{$_} = 1 }
  }
}

use Data::Dumper;
print Dumper \%opts;
die;

my $what = shift || die "usage: $0 file\n";
my $real = File::Spec->rel2abs($what);
die "error: could not determine realpath from $what\n" unless $real;

my @pathbits = File::Spec->splitdir($real);
die "error: unable to split realpath: $real" unless @pathbits;

my $current = '';
for my $filename (@pathbits) {
  $current = File::Spec->catdir($current, $filename);
  my $filedata = getfileinfo $current;

  unless ($filedata) {
    die "error: no data about $current\n";
  }

  # TODO means of supplying output fields and their order?
  print join " ", map $filedata->{$_},
   qw(type unix_mode_octal unix_user unix_group name);
  print ' -> ', $filedata->{link} if exists $filedata->{link};
  print "\n";
}

# returns various information about specified file in hash reference
sub getfileinfo {
  my $file = shift;

  my %filedata;
  $filedata{name} = $file;
  @filedata{qw(unix_mode unix_uid unix_gid)} = (lstat $file)[2, 4, 5];

  return unless defined $filedata{unix_mode};

  # TODO means of converting unix mode to drwx------ format?

  $filedata{unix_mode_octal} = sprintf "%04o", $filedata{unix_mode} & 07777;

  $filedata{type} = $filetype{sprintf "%07o", $filedata{unix_mode} & 0170000};
  $filedata{link} = readlink $file if $filedata{type} eq 'l';

  $filedata{unix_user}  = getpwuid $filedata{unix_uid} || $filedata{unix_uid};
  $filedata{unix_group} = getgrgid $filedata{unix_gid} || $filedata{unix_gid};

  return \%filedata;
}
