.Dd December 10 2017
.Dt RUBBLED 1
.nh
.Os
.Sh NAME
.Nm rubbled
.Nd reports if hosts are blacklisted
.Sh SYNOPSIS
.Bk -words
.Nm
.Op Ar - | host-or-ip4addr Op ..
.Ek
.Sh DESCRIPTION
.Nm
looks up the given hosts or IP addresses and reports whether those hosts
are listed in any of several blacklists (RBL) used to block spammers.
Hosts are read from standard input if none are given at the command
line, or also if the single argument
.Ar -
is given.
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
.Pp
.Dl $ Ic rubbled 192.0.2.42
.Dl $ Ic rubbled 162.144.157.48
.Dl 162.144.157.48 zen.spamhaus.org. CSS (snowshoe)
.Dl $
.Sh SEE ALSO
.Xr dig 1 ,
.Xr host 1
.Sh AUTHOR
.An Jeremy Mates
.Sh CAVEATS
IPv6 is not yet searched for.
