CFLAGS=-std=c99 -O3 -Wall -pedantic -fno-diagnostics-color -fstack-protector-all -fPIC -fPIE -pie -pipe

blocksig: blocksig.c

jitterbits: jitterbits.c

obdurate: obdurate.c

sigint-on: sigint-on.c

slay-self: slay-self.c

clean:
	git clean --force -x

.PHONY: clean
