.Dd August 15 2019
.Dt FBD 1
.nh
.Os
.Sh NAME
.Nm fbd
.Nd find files by date
.Sh SYNOPSIS
.Bk -words
.Nm
.Op Fl 0LPqx
.Op Fl a Ar around
.Op Fl b Ar before
.Op Fl s Ar mca
.Cm file
.Ar file
.Op Ar file ..
.Nm
.Op Fl 0LPqx
.Op Fl a Ar around
.Op Fl b Ar before
.Op Fl s Ar mca
.Cm epoch
.Ar epoch
.Op Ar file ..
.Ek
.Sh DESCRIPTION
.Nm
prints file names that have the same (or similar) epoch times as a given
.Cm file
or the given
.Cm epoch
time. Files are search for recursively in the given filenames, or
lacking those from the current directory.
Options:
.Bl -tag -width Ds
.It Fl 0
Null delimit the output filenames.
.It Fl L
Logical search, see
.Xr fts 3
for what this means.
.It Fl P
Physical filesystem search, the default.
.It Fl a Ar timespec
Non-exact match of plus or minus
.Ar timespec
seconds
.Qq around
the reference epoch, specified by seconds or in
the shorthand
.Ar 2m3s
form. Becomes
.Qq after
if
.Fl b
is specified.
.It Fl b Ar timespec
Non-exact match before the reference epoch. Same input format as for
.Fl a .
.It Fl s Ar mca
.Xr stat 2
field to test, modification time by default.
.It Fl q
Be quiet about various warnings (looped filesystems and such).
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
Find files in a given directory modified in the hour around the
given file:
.Pp
.Dl $ Ic fbd -a 1h file foo /given/dir
.Sh SEE ALSO
.Xr find 1 ,
.Xr findin 1 ,
.Xr findup 1 ,
.Xr getpof 1 ,
.Xr stat 1
.Sh AUTHOR
.An Jeremy Mates
.Sh HISTORY
Written in 2003 and fiddled with since then. The interface changed in
2019 when the code was rewritten.
.Pp
Modern systems offer file or kernel tracing facilities (ktrace, strace,
sysdig, etc) that may make this code less useful than it once was, which
was to detect what files had been installed around a particular time
based on the stat values.
