#!/bin/sh
#
# findup - search for a file in the current and any parent directories
# of the current working directory. Prints the first directory
# containing the matching filename, or exits with a non-zero exit
# status. Might be used in various other scripts in the sial.org scripts
# repository.
#
# Example usage: findup -H .git

# Whether to make less noise
QUIET=0

# Abort upward search if reach $HOME, even if the desired file exists
# in $HOME
NO_ESCAPE_HOME=0

OPT=
while getopts qH OPT; do
  case $OPT in
    q)
      QUIET=1
    ;;
    H)
      NO_ESCAPE_HOME=1
    ;;
  esac
done
shift `expr $OPTIND - 1`

SEARCH_FOR=$1
if [ -z "$SEARCH_FOR" ]; then
  echo "Usage: `basename $0` [-q] [-H] filename" >&2
  exit 64
fi

EXIT_STATUS=1
PREVIOUS_DIR=
while [ 1 ]; do
  CURRENT_DIR=`pwd`

  if [ $NO_ESCAPE_HOME -eq 1 -a "z$CURRENT_DIR" = "z$HOME" ]; then
    break
  fi

  # TODO option to supply the test (e.g. -d or -f or etc?) -- might have
  # some security or run-random-program concerns...
  if [ -r "$SEARCH_FOR" ]; then
    [ $QUIET -eq 0 ] && echo $CURRENT_DIR
    EXIT_STATUS=0
    break
  fi

  if [ "$CURRENT_DIR" = "$PREVIOUS_DIR" ]; then
    break
  fi

  PREVIOUS_DIR=$CURRENT_DIR
  cd .. || break
done

exit $EXIT_STATUS
