.Dd December  3 2017
.Dt FINDUP 1
.nh
.Os
.Sh NAME
.Nm findup
.Nd search for directory that contains a given filename
.Sh SYNOPSIS
.Bk -words
.Nm
.Op Fl dfqH
.Ar wanted
.Op Ar directory-path
.Ek
.Sh DESCRIPTION
.Nm
searches for the
.Ar wanted
file in the current directory and on up to the root directory, printing
the name of the directory that contains
.Ar wanted
or otherwise printing nothing and exiting with a non-zero code.
Options:
.Bl -tag -width -indent
.It Fl d
Use the is-directory test on
.Ar wanted .
The default test is whether the file is readable.
.It Fl f
Use the is-regular-file test on
.Ar wanted .
.It Fl q
Emit nothing, only indicate result via exit status.
.It Fl H
Abort the upwards search if the search passes outside of the
.Dv HOME
directory for the user running
.Nm .
.El
.Pp
An optional
.Ar directory-path
as the second argument allows a custom working directory to be
specified for the search; by default, the value from
.Xr getcwd 3
is used. All paths involved will be run through
.Xr realpath 3
to normalize them.
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
A common task would be to determine whether one is under a git
repository and if so what directory contains said repository without
escaping from your own home directory, in the event someone placed a
.Pa .git
directory somewhere between / and $HOME.
.Pp
.Dl $ Ic findup -d -H .git
.Dl /home/jdoe/src/scripts
.Dl $ 
.Pp
The
.Dv HOME
environment variable can be customized to prevent searches from escaping
out of some other directory tree:
.Pp
.Dl $ Ic cd /var/repository/some/foo/where
.Dl $ Ic HOME=/var/repository findup -H bla
.Pp
If
.Ar wanted
begins with a slash then the search will only be done from the
.Pa /
directory
.Pp
.Dl $ Ic findup /etc/passwd
.Dl /
.Dl $ 
.Pp
though for such cases
.Xr test 1
or the shell equivalent (if available) would be a much better option.
.Pp
.Dl $ Ic test -e /etc/passwd && echo yea
.Dl yea
.Dl $ Ic [[ -e /etc/passwd ]] && echo yea
.Dl yea
.Dl $ 
.Sh SEE ALSO
.Xr find 1 ,
.Xr findin 1 ,
.Xr getpof 1 ,
.Xr pwd 1 ,
.Xr realpath 3 ,
.Xr test 1
.Sh AUTHOR
.An Jeremy Mates
