.Dd December 20 2016
.Dt FINDIN 1
.nh
.Os
.Sh NAME
.Nm findin
.Nd find files in PATH or other lists of directories
.Sh SYNOPSIS
.Nm
.Bk -words
.Op Fl 0q
.Ar glob
.Op Ar envvar|-
.Ek
.Sh DESCRIPTION
.Nm
performs a glob search using the first argument in each of the
directories present in the
.Ev PATH
environment variable, or instead using the given environment variable
name, such as
.Ev MANPATH .
If 
.Ar -
is specified the list of directories to search is read from standard
input, one per line.
Options:
.Bl -tag -width -indent
.It Fl 0
Specifies that the input directories given on standard input and output
results will be NUL delimited. Environment variables will be colon-
split, regardless.
.It Fl q
Emit less noise from in particular
.Xr glob 3
calls at cost of perhaps missing errors.
.El
.Sh ENVIRONMENT
PATH is used by default; any arbitrary colon-delimited environment
variable can be used if specified as the second argument to the program.
Note that certain shell variables are not exported so will not be
available to
.Nm .
.Pp
.Dl % Ic echo ${(t)PATH}
.Dl scalar-export-special
.Dl % Ic echo ${(t)fpath}
.Dl array-special
.Pp
These could instead be passed in via standard input:
.Pp
.Dl % Ic print -l $fpath \&| findin _pgrep -
.Sh EXIT STATUS
.Ex -std
In particular, 2 indicates that no files were found and that no other
error occurred.
.Sh EXAMPLES
List manual pages that begin with
.Ar ls .
.Pp
.Dl $ Ic findin -q 'man*/ls*' MANPATH
.Pp
A contrived example to illustrate the use of
.Fl 0 .
.Pp
.Dl % Ic echo -n /etc$'\e0'/usr \&| findin -0 's*' \&| xargs -0 echo
.Sh SEE ALSO
Under the Z shell, this utility might be replaced with:
.Pp
.Dl % Ic print -l ${^fpath}/_pgrep(N)
.Dl % Ic print -l ${^path}/perl(N)
.Dl % Ic print -l ${^${(s.:.)PATH}}/perl(N)
.Pp
Otherwise,
.Xr find 1
itself may be used, possibly with a script to simplify the necessary
redressing of the environment variable:
.Pp
.Dl % Ic find `echo $MANPATH \&| tr ':' ' '` -name ...
.Pp
.Xr find 1 ,
.Xr findup 1 ,
.Xr getpof 1 ,
.Xr glob 3 ,
.Xr zshexpn 1 ,
.Xr zshparam 1
.Sh AUTHOR
Jeremy Mates
.Sh CAVEATS
.Dv GLOB_LIMIT
is not used; this utility must therefore not be exposed to attackers who
can supply arbitrary patterns to
.Xr glob 3 .
.Pp
.Nm
does not much check the input for validity e.g. if
.Ev PATH
contains elements, or that the elements even exist.
.Pp
The paths generated are not checked whether they exceed
.Dv PATH_MAX .
