#!/bin/sh
#
# Moves files into a predetermined target directory. TODO I think I'm
# using poorly named ZSH functions for this now (see copyto dcos),
# probably should retire this script?
#
# TODO need copy option somehow.
#
# The author disclaims all copyrights and releases this script into the
# public domain.

if [ -z $FTARGET ]; then
  echo "error: must specify FTARGET env. variable as target directory" >&2
fi

if [ -z $1 ]; then
  echo "usage: `basename $0` file [file2 ...]" >&2
fi

copyto -m "$@" $FTARGET >/dev/null
