#!/bin/sh
#
# Moves files into a predetermined target directory. TODO I think I'm
# using poorly named ZSH functions for this now (see copyto docs),
# probably should retire this script?
#
# TODO need copy option somehow.

if [ -z $1 ]; then
  echo "usage: `basename $0` file [file2 ...]" >&2
  exit 64
fi

if [ -z $FTARGET ]; then
  echo "error: must specify FTARGET env. variable as target directory" >&2
  exit 65
fi

copyto -m "$@" $FTARGET >/dev/null
