.Dd May 20 2017
.Dt GLF 1
.nh
.Os
.Sh NAME
.Nm glf
.Nd get latest file
.Sh SYNOPSIS
.Nm
.Bk -words
.Op Fl e Ar exclude-regex
.Op Ar file-regex
.Op Ar directory
.Ek
.Sh DESCRIPTION
.Nm
gets the most recently modified file in the given directory, matching
all files unless a
.Ar file-regex
is given and using the current working directory unless a
.Ar directory
is given.
Options:
.Bl -tag -width Ds
.It Fl e Ar exclude-regex
A regular expression that will be used to exclude otherwise
matching files.
.El
.Sh EXIT STATUS
.Ex -std
An exit code of 2 indicates that no latest file was found.
.Sh EXAMPLES
Get the latest lilypond file, minus sub-part files that use a
.Pa piece.subpart.ly
convention.
.Pp
.Dl $ Ic glf -e '\e.[^.]+\e.ly$' '\e.ly$'
.Sh SEE ALSO
.Xr fbd 1 ,
.Xr find 1 ,
.Xr ls 1
.Sh AUTHOR
.An Jeremy Mates
