#!/usr/bin/env expect
#
# The current directory, minus the home directory (which may vary for a
# user between different systems) so that e.g. scp or rsync commands can
# be used along the lines of (assuming parallel directory structures on
# the two hosts involved):
#
#   cd ~/...
#   scp ... otherhost:`here`

if {[llength $argv] == 1} {
    set workdir [lindex $argv 0]
    if {[string length $workdir] == 0} {
        puts stderr "Usage: here \[directory-path]"
        exit 1
    }
} else {
    set workdir [pwd]
}

set workdir [file normalize $workdir]
set homedir [file normalize ~]
puts [regsub "^$homedir[file separator]" $workdir ""]
