#!/usr/bin/env perl
#
# ignore - adds input to the git ignore list

use 5.16.0;
use warnings;
use Cwd qw(getcwd);
use File::AtomicWrite;
use File::Slurper qw(read_lines);

die "Usage: ignore file-or-pattern [..]\n" unless @ARGV;

if ( system(qw{findup -H -q .git}) == 0 ) {
    my %ignore;
    eval { @ignore{ read_lines ".gitignore" } = () };
    @ignore{@ARGV} = ();
    my $aw = File::AtomicWrite->new( { file => ".gitignore" } );
    my $fh = $aw->fh;
    say $fh $_ for sort keys %ignore;
    $aw->commit;
    exit;
}

die "no repository found above '", getcwd, "'\n";
