.Dd November 22 2017
.Dt IS-CHANGED 1
.nh
.Os
.Sh NAME
.Nm is-changed
.Nd runs command on file content change
.Sh SYNOPSIS
.Bk -words
.Nm
.Ar time-spec
.Ar command
.Ar
.Ek
.Sh DESCRIPTION
.Nm
checks each
.Ar time-spec
seconds whether the contents of the given files have changed and if so
runs the given
.Ar command .
The
.Ar time-spec
may be given in raw seconds or in the
.Cm 1m3s
shorthand form.
.Pp
The check interval is in addition to however long the
.Ar command
takes to run.
.Sh EXIT STATUS
Unless there is an error (and thus a non-zero exit),
.Nm
will loop forever.
.Sh EXAMPLES
.Dl $ Ic is-changed 3s 'make foo && ...' foo.c ...
.Sh SEE ALSO
.Xr entr 1 ,
.Xr is-changed-mtime 1
.Pp
Various filesystem notification services may be more suitable, should
those be available.
.Sh AUTHOR
.An Jeremy Mates
