.Dd January  6 2017
.Dt LLCOUNT 1
.nh
.Os
.Sh NAME
.Nm llcount
.Nd length of line tool
.Sh SYNOPSIS
.Nm
.Bk -words
.Op Fl x
.Op Ar file|-
.Ek
.Sh DESCRIPTION
.Nm
displays the line number, the start position of that line, and
the length of the line of the file mentioned or failing that or
if the file is
.Ar -
the data from standard input is used. The file data is then displayed
after this metadata.
.Pp
The
.Fl x
option specifies that hex should be used instead of decimal for the line
start position.
.Sh EXIT STATUS
.Ex -std llcount
.Sh SEE ALSO
.Xr hexdump 1 ,
.Xr wc 1
.Sh AUTHOR
.An Jeremy Mates
