#!/bin/sh
#
# Utility to set FTARGET, which is used by various other scripts I
# employ. (cd and fmmd, mostly.) The ZSH sighandle directory related
# stuff requires:
#
#   _shared_rc() {
#     for f in ~/.zsh/sighandle/USR1/*(N); do
#       . $f
#     done
#   }
#   TRAPUSR1() {
#     _shared_rc
#   }
#   _shared_rc
#
# And appropriate use of some form of mkdir.

set_ftarget () {
  echo export FTARGET=`pwd` > $HOME/.zsh/sighandle/USR1/set-ftarget
  exec allsh "export FTARGET=\"`pwd`\""
}

do_chdir () {
  (
    builtin cd "$1" || exit 1
    set_ftarget
  )
}

if [ -z "$1" ]; then
  set_ftarget
else
  if [ -d "$1" ]; then
    do_chdir "$1"
  elif [ -f "$1" ]; then
    do_chdir "`dirname \"$1\"`"
  else
    echo "`basename \"$0\"`: not a file nor directory: $1" >&2
    exit 1
  fi
fi
