#!/bin/sh
#
# Reveals files in the Finder under Mac OS X.
#
# The author disclaims all copyrights and releases this script into the
# public domain.

if [ -z "$1" ]; then
  echo "usage: `basename $0` files"
  exit 64
fi
open -a Finder "$@"
