#!/bin/sh
#
# Lists subdirectories of the current directory, or the specified
# directories if any given on command line. Returns 0 if subdirectories,
# 1 otherwise. Use the -q flag to suppress the listing. Used by various
# other scripts in the sial.org script repository.

QUIET=0
RETURN=1

scandir () {
  for file in *; do
    if [ -d "$file" ]; then
      RETURN=0

      # if quiet, single subdir enough
      if [ $QUIET -eq 1 ]; then
        exit $RETURN
      fi

      echo $file
    fi
  done
}

OPT=
while getopts q OPT; do
  case $OPT in
    q)
      QUIET=1
      shift
    ;;
  esac
done
shift `expr $OPTIND - 1`

if [ $# -eq 0 ]; then
  scandir
else
  for dir in "$@"; do
    if [ -d "$dir" ]; then
    (
      cd "$dir" && scandir
    )
    else
      if [ $QUIET -eq 1 ]; then
        echo "warning: not a directory: $dir" >&2
      fi
    fi
  done
fi

exit $RETURN
