#!/usr/bin/env perl
# uvi - edit files without changing the access times

die "Usage: uvi file [file2 ..]\n" unless @ARGV;

for my $file (@ARGV) {
    die "not a file: '$file'\n" unless -f $file;
    push @restore, [ ( stat $file )[ 8, 9 ], $file ];
}

$ret = 0;
system( $ENV{EDITOR} || 'vi', @ARGV ) == 0 or $ret = 1;

foreach (@restore) {
    unless ( utime @$_ ) {
        warn "could not restore ", $_->[-1], " to orig times: $!\n";
        $ret = 1;
    }
}
exit $ret;
