birds: aaarghs.c birds.c
	$(CC) $(CFLAGS) -o birds aaarghs.c birds.c

orb-of-fire: aaarghs.c orb-of-fire.c
	$(CC) $(CFLAGS) -o orb-of-fire aaarghs.c orb-of-fire.c

clean:
	@-rm -f birds orb-of-fire *.core >/dev/null 2>&1
