#!/bin/sh
#
# Script to work with shell signal trapping to run shell commands in
# all shells. For example using zsh, set the following in ~/.zshrc:
#
# TRAPUSR2() {
#   [ -f ~/.sh-sourceall ] && . ~/.sh-sourceall
# }
#
# Warning! This script has various potential security problems,
# especially where multiple users are involved with a shared account
# (root), or where write access to the ~/.sh-sourceall file is possible
# by untrusted users, e.g. via untrusted code injection into the file
# in question, especially if ~/.sh-sourceall is on an insecure network
# file system.

# routine to signal a process matching an expression with a
# specified signal.
#
# another option might be to have shells write their pids to somewhere
# like ~/.zsh/shellpids/$$, then just run through that file list, though
# cleanup of the files could be problematic
signalit () {
  PATTERN=$1
  SIGNAL=$2

  # TODO this ps not portable to things like Solaris... but I don't use
  # that. grep -v login to exclude login ... zsh on Mac OS X which must
  # not be signaled. Ugh.
  ps xwwo pid,command | grep -v login | while read pid command; do
    if echo $command | egrep -- "$PATTERN" >/dev/null; then
      kill -$SIGNAL $pid
    fi
  done
}

if [ -z "$1" ]; then
  echo "usage: `basename $0` [shell statements|-]"
  exit 64
fi

# TODO test new expression first in a sub-shell to ensure it will work
# before running it everywhere?

# KLUGE just clobber a known file, which will cause problems if multiple
# 'allsh' are run or if multiple users are involve somehow.
if [ "$1" = '-' ]; then
  cat > $HOME/.sh-sourceall
else
  echo "$@" > $HOME/.sh-sourceall
fi

# KLUGE this signal is dependent on how the shell shows itself via the
# ps command run... need to add more shells, maybe figure out something
# more portable?
signalit '(bin/|-)zsh' USR2
