#!/bin/sh
#
# $Id$
#
# The author disclaims all copyrights and releases this script into the
# public domain.
#
# Prints the date in a format to the liking of the author.

DODATE=no
DOTIME=no
DOTIME_ZONE=no
QUERY=

# process arguments
OPT=
while getopts dtz OPT; do
  case $OPT in
    d)
      DODATE=yes
    ;;
    t)
      DOTIME=yes
    ;;
    z)
      DOTIME_ZONE=yes
    ;;
  esac
done
shift $(($OPTIND - 1))

# custom arguments for custom formats
if [ "$1" = "rpm" ]; then
  [ -z "$MY_REALNAME" ] && MY_REALNAME=`whoami`
  [ -z "$MY_EMAIL" ] && MY_EMAIL="`whoami`@`hostname`"
  date "+* %a %b %d %Y $MY_REALNAME <$MY_EMAIL>"
  exit
fi
if [ "$1" = "dns" ]; then
  if [ -z "$2" ]; then
    SERIAL=00
  else
    SERIAL=$2
  fi
  date "+%Y%m%d$SERIAL"
  exit
fi

# form up query specification for date(1) command
if test $DODATE = yes ; then
  QUERY='%Y-%m-%d'
fi
if test $DOTIME = yes ; then
  QUERY="${QUERY:+$QUERY }%H:%M:%S"
fi
if test $DOTIME_ZONE = yes ; then
  QUERY=${QUERY:+$QUERY}%z
fi

date "+$QUERY"
