#!/bin/sh
#
# findup - search for a file in the current and any parent directories
# of the current working directory. Prints the first directory
# containing the matching filename, or exits with a non- zero exit
# status. Might be used in various other scripts in the sial.org scripts
# repository.
#
# The author disclaims all copyrights and releases this script into the
# public domain.

OPT=
QUIET=0
while getopts q OPT; do
  case $OPT in
    q)
      QUIET=1
    ;;
  esac
done
shift $(($OPTIND - 1))

SEARCH_FOR=$1
if [ -z "$SEARCH_FOR" ]; then
  echo "Usage: `basename $0` filename" >&2
  exit 1
fi

EXIT_STATUS=1
PREVIOUS_DIR=
while [ 1 ]; do
  CURRENT_DIR=`pwd`

  # TODO option to supply the test (e.g. -d or -f or etc?) -- might have
  # some security or run-random-program concerns...
  if [ -e "$SEARCH_FOR" ]; then
    [ ! $QUIET ] && echo $CURRENT_DIR
    EXIT_STATUS=0
    break
  fi

  if [ "$CURRENT_DIR" == "$PREVIOUS_DIR" ]; then
    break
  fi

  PREVIOUS_DIR=$CURRENT_DIR
  cd .. || break
done

exit $EXIT_STATUS
