#!/usr/bin/perl
#
# Wrapper to sign multiple files with gpg.
#
# The author disclaims all copyrights and releases this script into the
# public domain.

use strict;
use warnings;

my @gpg_sign_cmd =
  qw(gpg --passphrase-fd 0 --quiet --sign --detach-sign --armor);

if ( !@ARGV ) {
  die "Usage: $0 file [file2 ..]\n";
}

print "Passphrase: ";

use Term::ReadKey qw(ReadMode);
ReadMode('noecho');
my $phrase = <STDIN>;
ReadMode('restore');
print "\n";

chomp $phrase;

for my $file (@ARGV) {
  next unless -f $file;

  # TODO use 'rpm --addsign' for RPM, though how pass password to it?
  gpg_sign($file);
}

sub gpg_sign {
  my $file = shift;
  open SEND_PASS,          '|-'
    or exec @gpg_sign_cmd, $file
    or die "error: exec failed: errno=$!\n";
  print SEND_PASS $phrase;
  close SEND_PASS or die "error: non-zero exit from command\n";
}
