#!/usr/bin/env perl
#
# Makes noise to syslog via logger(1). Run perldoc(1) on this file for
# additional documentation.

use strict;
use warnings;

use Carp;
use Getopt::Std;

my @facility = qw(
auth
authpriv
cron
daemon
ftp
kern
lpr
mail
news
security
syslog
user
uucp
local0
local1
local2
local3
local4
local5
local6
local7
);

my @level = qw(
emerg
alert
crit
err
warning
notice
info
debug
);

for my $l (@level) {
  for my $f (@facility) {
    system 'logger', @ARGV, '-p', "$f.$l", '--', "yakking to $f.$l";
  }
}

exit;

# a generic help blarb
sub help {
  warn <<"HELP";
Usage: $0

Tests what levels/facilities are handled by syslog.

Options:
  -h/-?  Display this message

Run perldoc(1) on this script for additional documentation.

HELP
  exit 64;
}

=head1 NAME

syslog-yak - tests what levels/facilities are handled by syslog

=head1 SYNOPSIS

  $ syslog-yak

=head1 DESCRIPTION

=head2 Overview

Tests what levels/facilities are handled by syslog.

=head2 Normal Usage

  $ syslog-yak

Any command line arguments are passed to logger(1).  The script
attempts to set the B<-p> I<priority> option to logger(1) internally.

=head1 EXAMPLES

None yet.

=head1 BUGS

=head2 Reporting Bugs

Newer versions of this script may be available from:

http://github.com/thrig/sial.org-scripts/tree/master

If the bug is in the latest version, send a report to the author.
Patches that fix problems or add new features are welcome.

=head2 Known Issues

No known bugs.

=head1 SEE ALSO

perl(1)

=head1 AUTHOR

thrig - Jeremy Mates (cpan:JMATES) C<< <jmates at cpan.org> >>

=head1 COPYRIGHT

Copyright (c) 2015 Jeremy Mates

     Permission to use, copy, modify, and/or distribute this software for
     any purpose with or without fee is hereby granted, provided that the
     above copyright notice and this permission notice appear in all
     copies.

     THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
     WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
     WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
     AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
     DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA
     OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
     TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
     PERFORMANCE OF THIS SOFTWARE.

=cut
