#!/bin/sh
#
# yak - diagnostic tool that saves invocation details to a temporary
# file. another option is to instead use tools like strace or sysdig
myname=`basename "$0"`
yakout=`mktemp "/tmp/yak.$myname.XXXXXXXXXX"` || exit 1
chmod go-r "$yakout"
(  printf "$0 $@\npid=$$\n"
   id  ; groups ; printf "\n"
   tty ; printf "\n"
   env ; printf "\n"
   if [ -t 0 ]; then
      printf "istty\n"
   else
      cat
   fi
) >> "$yakout"
