#!/bin/sh
#
# yak-ssh - like yak, but for SSH_ORIGINAL_COMMAND via SSH sessions. in
# $HOME/.ssh/authorized_keys add a command restriction for the key
#
#   command="/path/to/yak-ssh" ssh-ed25519 AAAA...
#
# then use SSH and inspect the ssh-yak.* output for the command and env
# gleanings. a shorter version less concerned with the env and tmp
# security needs might run something like
#
#   #!/bin/sh
#   printf "$SSH_ORIGINAL_COMMAND\n" >> "$HOME"/tmp/ssh-yak
#   eval "$SSH_ORIGINAL_COMMAND"
#
# and because I keep forgetting these
#
#   SSH_CLIENT="srcip srcport dstport"
#   SSH_CONNECTION="srcip srcport dstip dstport'
#
# NOTE software may already support limited access via ssh e.g. git-shell(1)
yakout=`mktemp /tmp/yak-ssh.XXXXXXXXXX` || exit 1
chmod go-r "$yakout"
(  printf "$SSH_ORIGINAL_COMMAND\n\n"
   if [ -t 0 ]; then
      tty
   else
      printf "no tty on stdin\n"
   fi
   printf "\n" ; env
) >> "$yakout"
# if there's no fancy shell syntax then instead
#exec $SSH_ORIGINAL_COMMAND
eval "$SSH_ORIGINAL_COMMAND"
