#!/usr/bin/perl -l
#
# Twiddles case.
#
# The author disclaims all copyrights and releases this script into the
# public domain.

use Getopt::Std;
my %opts;
getopts('ul', \%opts);

END {
  # Report problems when writing to stdout (perldoc perlopentut)
  unless ( close(STDOUT) ) {
    die "error: problem closing STDOUT: $!\n";
  }
}

chomp(@ARGV = <STDIN>) unless @ARGV;

for (@ARGV) {
  print $opts{l} ? lc : uc;
}
