#!/usr/bin/perl -l
#
# Twiddles case.
#
# The author disclaims all copyrights and releases this script into the
# public domain.

use Getopt::Std;
my %opts;
getopts('ul', \%opts);

chomp(@ARGV = <STDIN>) unless @ARGV;

for (@ARGV) {
  print $opts{l} ? lc : uc;
}
