#!/bin/sh
#
# $Id$
#
# The author disclaims all copyrights and releases this script into the
# public domain.
#
# Expands source RPMs via rpm2cpio(8) and cpio(1) into directories under
# the current directory.

if [ -z "$1" ]; then
  echo "usage: `basename $0` srcrpm [srcrpm2 .. srcrpmN]"
  exit 1
fi

for file in "$@" ; do
  if [ -f $file ]; then
    dir=`rpm -qp --queryformat '%{NAME}' $file`

    if [ -z "$dir" ]; then
      dir="$file.d"
      echo "notice: could not determine package name for $file, using $dir" >&2
    fi

    if [ -e $dir ]; then
      echo "warning: $dir already exists, skipping $file" >&2
      continue
    fi

    mkdir $dir
    rpm2cpio $file | ( cd $dir && cpio -id 2>/dev/null )
    echo $dir
  else
    echo "notice: no such file $file" >&2
  fi
done
