#!/usr/bin/perl
#
# $Id$
#
# The author disclaims all copyrights and releases this script into the
# public domain.
#
# Converts epoch times to human parsable dates.

require 5;
use strict;

use POSIX qw(strftime);

use Getopt::Std;
my %opts;
getopts('ef:gl', \%opts);

my $format = $opts{'f'} || "%Y-%m-%d %H:%M:%S";

# gmtime or localtime, depending on program name or options supplied
my $function = 'localtime';
$function = 'gmtime' if $0 eq 'epoch2gmdate';
$function = ($opts{'g'}) ? 'gmtime' : 'localtime';
$function = ($opts{'l'}) ? 'localtime' : 'gmtime';

die "usage: $0 [-f fmt] [-g|-l] [-e] epoch [epoch ...]\n" unless @ARGV;

for my $epoch (@ARGV) {
  print $epoch, ' ' if $opts{'e'};
  print strftime $format, eval "$function $epoch";
  print "\n";
}
