#!/usr/bin/perl -w
#
# $Id$
#
# The author disclaims all copyrights and releases this script into the
# public domain.
#
# Given a date, will attempt to return the epoch time for that date.

use Date::Manip;
use File::Basename qw(basename);
my $basename = basename $0;

die "usage: $basename date\n" unless @ARGV;

print UnixDate(ParseDate($ARGV[0]), "%s"), "\n";
