#!/usr/bin/perl -w
#
# Given a date, will attempt to return the epoch time for that date.
#
# The author disclaims all copyrights and releases this script into the
# public domain.

use Date::Manip;
use File::Basename qw(basename);
my $basename = basename $0;

END {
  # Report problems when writing to stdout (perldoc perlopentut)
  unless ( close(STDOUT) ) {
    die "error: problem closing STDOUT: $!\n";
  }
}

die "usage: $basename date\n" unless @ARGV;

print UnixDate(ParseDate($ARGV[0]), "%s"), "\n";

=pod PREREQUISITES

Date::Manip

=pod OSNAMES

any

=pod SCRIPT CATEGORIES

Utilities

=cut
