CFLAGS += `pkg-config --cflags --libs goptfoo jkiss`

byteswap: byteswap.c

byteswapprime: byteswapprime.c

replacebytes: replacebytes.c

twiddle: twiddle.c

clean:
	@-rm -f byteswap byteswapprime replacebytes twiddle *.core 2>/dev/null
