.Dd August 31, 2015
.Dt REPLACEBYTES 1
.Ds
.Sh NAME
.Nm replacebytes
.Nd alters files in-place with data from a source file
.Sh SYNOPSIS
.Nm
.Bk -words
.Op Fl f Ar file | Fl m Ar msg
.Op Fl O Ar offset
.Op Fl t Ar trunc
.Ar file
.Op Ar file2 ..
.Ek
.Sh DESCRIPTION
Alters files in-place with the specified bytes from the source file (or
with the given message) at the specified offset in any files listed.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl f Ar file
Source file to read the replacement bytes from. Mandatory, or instead
specify the data to write with the
.Fl m
flag. The source file must have data in it.
.It Fl m Ar message
Data to write into file. The message can be the empty string, presumably
used in conjunction with the
.Fl t
flag.
.It Op Fl O Ar offset
Offset at which to write the data in the output files.
.It Op Fl t Ar truncate
Truncate (or extend!) the output file(s) to the specified offset. This
is done after the replacement of bytes.
.El
.Sh CAVEATS
The files will be altered in-place, without locking. Such edits are not
atomic, and other (more or less) simultaneous changes to the files might
cause corruption. Adjust the workflow to copy and rename the files, if
necessary, and ensure that backups have been made before using this tool
on any data you care about.
.Sh EXIT STATUS
.Ex -std replacebytes
.Sh SEE ALSO
.Xr dd 1 ,
.Xr hexdump 1 ,
.Xr llcount 1
.Sh AUTHOR
Jeremy Mates
