#!/bin/sh
#
# Better UI wrapper for pngcrush.

if [ -z "$1" ]; then
  echo "Usage: `basename $0` png-image [...]" >&2
  exit 64
fi

for file in "$@"; do
  TMPFILE=`mktemp .crush-png-tmp.XXXXXXXXXX` || exit 1
  pngcrush -brute -fix -reduce "$file" $TMPFILE 1>/dev/null || {
    rm $TMPFILE
    exit 1
  }
  chmod a+r "$TMPFILE"
  mv $TMPFILE "$file"
  
  # Undo name breakage Omnigraffle (v.4 and earlier) applies to PNG
  if echo "$file" | grep '\.gnp$' >/dev/null; then
    FILE_PREFIX=`basename "$file" .gnp`
    mv "$file" "$FILE_PREFIX.png"
  fi
done
