#!/usr/local/bin/sh
WIF=en1
if `networksetup -getairportpower "$WIF" | grep -qi On`; then
    # prior DHCP lease will ARP-spam the new network with old info; clear
    # that to leak less information
    sudo arp -a -d
    sudo ipconfig set "$WIF" NONE
    apple-randomize-macaddr
    networksetup -setairportpower "$WIF" off
    echo off
    exit 1
else
    sudo ipconfig set "$WIF" DHCP
    sudo ipconfig set "$WIF" AUTOMATIC-V6
    # I've totally replaced the usual Apple firewall rules
    sudo pfctl -e -F all -f /etc/pf.conf >/dev/null
    networksetup -setairportpower "$WIF" on
    echo on
    exit 0
fi
