requires 'File::HomeDir';
requires 'File::Slurper';
requires 'HTTP::Tiny';
requires 'IO::Socket::INET';
requires 'JSON::MaybeXS';
requires 'LWP::Protocol::https';
requires 'Sys::Hostname';
requires 'URI';
