#!/usr/bin/perl -l
#
# Converts hex format IP address into IPv4 address humans like.
#
# The author disclaims all copyrights and releases this script into the
# public domain.

END {
  # Report problems when writing to stdout (perldoc perlopentut)
  unless ( close(STDOUT) ) {
    warn "error: problem closing STDOUT: $!\n";
    exit 74;
  }
}

chomp(@ARGV = <STDIN>) unless @ARGV;

for my $input (@ARGV) {
  print join ".", unpack "C4", pack "H*", $input;
}
