#!/usr/bin/env perl
#
# Converts hex format IP address into IPv4 address humans like.

END {
  # Report problems when writing to stdout (perldoc perlopentut)
  unless ( close(STDOUT) ) {
    warn "error: problem closing STDOUT: $!\n";
    exit 74;
  }
}

chomp(@ARGV = <STDIN>) unless @ARGV;

for my $input (@ARGV) {
  print join ".", unpack "C4", pack "H*", $input;
  print "\n";
}
