#!/usr/bin/env perl

my $PREFIX = '/tftpboot/pxelinux.cfg/';

chomp( @ARGV = readline *STDIN ) unless @ARGV;

for my $arg (@ARGV) {
    $arg =~ tr/A-F:/a-f-/;
    $arg =~ s/^/01-/;

    print $PREFIX, $arg, "\n";
}
