#!/usr/bin/perl
use 5.24.0;
use warnings;
# 'lower' due to RFC 5952
use NetAddr::IP qw(:lower);

my $method = shift // die "Usage: netaddrip method [args ..]\n";

my %dispatch = (
    split => sub {
        # argument  127.0.0.1/23 24  splits that into two /24 subnets, etc
        my $net = NetAddr::IP->new( shift @ARGV );
        say for $net->splitref(@ARGV)->@*;
    },
);

no_method($method) if !exists $dispatch{$method};
$dispatch{$method}->();

sub no_method { die "no such method '$_[0]'\n" }
