.Dd November 22 2017
.Dt PORTPESTER 1
.nh
.Os
.Sh NAME
.Nm portpester
.Nd makes lots of TCP connections to a port
.Sh SYNOPSIS
.Bk -words
.Nm
.Op Fl 46nv
.Ar host
.Ar port
.Ek
.Sh DESCRIPTION
.Nm
floods the given target with lots of TCP connect calls; this may be
useful to test for buggy handling of such a state.
.Pp
Options:
.Bl -tag -width Ds
.It Fl 4
forces IPv4
.It Fl 6
forces IPv6
.It Fl n
skips hostname resolution
.It Fl v
makes things more verbose
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr nmap 1
.Sh AUTHOR
.An Jeremy Mates
