.Dd July 7, 2014
.Dt PORTPESTER 1
.nh
.Os
.Sh NAME
.Nm portpester
.Nd annoy your network admin
.Sh SYNOPSIS
.Nm portpester
.Bk -words
.Op Fl 46nv
.Ar host
.Ar port
.Ek
.Sh DESCRIPTION
.Nm
floods the given target with lots of TCP connect calls.
.Fl n
skips hostname resolution,
.Fl v
makes things more verbose, and
.Fl 4
or
.Fl 6
force IPv4 or IPv6. Otherwise, this tool is fairly incomplete, and may require digging around in the source or the use of some other network tool, depending on the need.
.Pp
.Sh EXIT STATUS
.Ex -std portpester
.Sh SEE ALSO
.Xr nmap 1
.Sh AUTHOR
.An Jeremy Mates
