.Dd January  6 2017
.Dt V4ADDR 1
.nh
.Os
.Sh NAME
.Nm v4addr
.Nd IPv4 address parser
.Sh SYNOPSIS
.Nm
.Bk -words
.Op Fl fqr
.Ar ipv4-address
.Ek
.Sh DESCRIPTION
.Nm
parses and prints a given IPv4 address.
.Pp
Options:
.Bl -tag -width Ds
.It Fl f
Prints the address in regular form (the default).
.It Fl q
will suppress diagnostic output should the address fail to parse.
.It Fl r
prints the address in reverse DNS form.
.El
.Pp
Note that the truncated 127.1 form that some software accepts is not
supported.
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
.Dl $ Ic v4addr 127.0.0.1
.Dl $ Ic v4addr -f 127.0.0.1
.Pp
.Dl $ Ic v4addr -r 127.0.0.1
.Sh SEE ALSO
.Xr v6addr 1
.Sh AUTHOR
.An Jeremy Mates
