.Dd January  6 2017
.Dt V6ADDR 1
.nh
.Os
.Sh NAME
.Nm v6addr
.Nd IPv6 address qualifier or ip6.arpa.ifier
.Sh SYNOPSIS
.Nm
.Bk -words
.Op Fl fqr
.Ar ipv6-address
.Ek
.Sh DESCRIPTION
.Nm
parses and prints the supplied IPv6 address.
.Pp
Options:
.Bl -tag -width Ds
.It Fl f
print the IPv6 address (the default).
.It Fl q
will supress diagnostic output should the address fail to parse.
.It Fl r
prints the address in reverse DNS ip6.arpa form, one that is likely
simpler to use than by having to parse the output from
.Xr sipcalc 1 .
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
.Dl $ Ic v6addr ::1
.Dl $ Ic v6addr -f ::1
.Pp
.Dl $ Ic v6addr -r ::1
.Sh SEE ALSO
.Xr sipcalc 1 ,
.Xr v4addr 1
.Sh AUTHOR
.An Jeremy Mates
