CFLAGS=-std=c99 -O2 -Wall -pedantic -fno-diagnostics-color -fstack-protector-all -fPIC -fPIE -pie -pipe

justblocks.t: justblocks.t.c

clean:
	@-rm -fr justblocks.t *.core *.dSYM 2>/dev/null

.PHONY: clean
