#!/bin/sh
#
# Tests XML files for validity via xmllint. Probably should just be a
# shell function?

if [ -z "$1" ]; then
  echo "Usage: `basename $0` xmlfile" >&2
  exit 64
fi

exec xmllint --noout "$@"
