#!/bin/sh
#
# $Id$
#
# The author disclaims all copyrights and releases this script into the
# public domain.
#
# Copies files into a predetermined target directory.

if [ -z $FTARGET ]; then
  echo "error: must specify FTARGET env. variable as target directory" >&2
fi

if [ -z $1 ]; then
  echo "usage: `basename $0` file [file2 ...]" >&2
fi

take "$@" $FTARGET
