#!/bin/sh
#
# $Id$
#
# The author disclaims all copyrights and releases this script into the
# public domain.
#
# Lists all known hosts from OpenSSH known_hosts files; see
# ssh_config(5) for details.

# KLUGE global ssh_known_hosts location may vary by system
KNOWN_HOSTS_FILES="$HOME/.ssh/known_hosts /etc/ssh/ssh_known_hosts"

{
  for f in $KNOWN_HOSTS_FILES; do
    if [ -f $f ]; then
      awk '{n = $1; split(n, a, ","); for (val in a) print a[val]}' $f
    fi
  done
} | sort | uniq
