#!/usr/bin/perl
#
# Utility script to tidy up long runs of presumably lilypond notes by a
# specified value (4 notes by default). Does not deal with much of any
# of actual lilypond format, as that would require a lexer or writing up
# something against a Parser::* or whatnot module.

use strict;
use warnings;

my $group_size = shift || 4;

while (<>) {
  s/^\s+//;
  s/((?:\S+(?:\s+|$)){$group_size})/  $1\n/g;
  print;
}
