#!/bin/sh
#
# $Id$
#
# The author disclaims all copyrights and releases this script into the
# public domain.
#
# Updates host keys found in named SSH known_hosts file.

BASENAME=`basename $0`

if [ -z $1 ]; then
  echo "usage: $BASENAME known_hosts-file" >&2
  exit 100
fi

KHF=$1

if [ ! -w $KHF ]; then
  echo "error: cannot write to known hosts file: file=$KHF" >&2
  exit 1
fi

TMPFILE=`mktemp -t $BASENAME.XXXXXXXX` || exit 1
trap "rm -f $TMPFILE" 0 1 2 13 15

awk '{print $1}' $KHF | \
  ssh-keyscan -t rsa,dsa -f - 2>/dev/null | \
  ssh-hkutil $KHF - > $TMPFILE || exit 1

if [ ! -s $TMPFILE ]; then
  echo "error: temporary file empty" >&2
  exit 1
fi

cmp -s $KHF $TMPFILE
STATUS=$?

if [ $STATUS -eq 1 ]; then
  mv $TMPFILE $KHF
elif [ $STATUS -gt 1 ]; then
  echo "error: cmp failed: status=$STATUS" >&2
fi
