#!/bin/sh
#
# Like yak, but for SSH_ORIGINAL_COMMAND via SSH sessions so that the
# exact commands used over SSH sessions can be logged. Actual command is
# run after this logging. Usage: in ~/.ssh/authorized_keys add a command
# statement prefixing the SSH key in question:
#
#   command="/path/to/yak-ssh" ssh-rsa AAAA...
#
# Then use SSH, inspect the ssh-yak.* output files for the command and
# env gleanings.
#
# The author disclaims all copyrights and releases this script into
# the public domain.

shortname=`basename $0`
shortname=${shortname:=ssh-yak}

#OUTPUT=/dev/null
OUTPUT=`mktemp -q /tmp/${shortname}.XXXXXXXXX`
if [ $? -ne 0 ]; then
  OUTPUT=/tmp/${shortname}.$$
fi

#logger -i -t $shortname "ssh-command is $SSH_ORIGINAL_COMMAND"

(
echo SSH-COMMAND::BEGIN
echo $SSH_ORIGINAL_COMMAND
echo SSH-COMMAND::END
echo

# shouldn't be set, unless perhaps `ssh -t` used for some reason
if test -t 0; then
  echo TTY::BEGIN
  tty
  echo TTY::END
else
  echo TTY:NONE
fi
echo

echo ENV::BEGIN
set
echo ENV::END
echo

) >> $OUTPUT

exec $SSH_ORIGINAL_COMMAND
