.Dd December 14 2018
.Dt UDP-SINK 1
.nh
.Os
.Sh NAME
.Nm udp-sink
.Nd accepts packets from
.Xr udp-sender 1
and emits statistics
.Sh SYNOPSIS
.Bk -words
.Nm
.Op Fl 46lN
.Op Fl c Ar statsinterval
.Op Fl d Ar delay
.Op Fl P Ar packetsize
.Fl p Ar port
.Ek
.Sh DESCRIPTION
.Nm
accepts packets from 
.Xr udp-sender 1
and emits statistics on the packets received. The packets contain a
counter value, possibly padded to
.Ar packetsize .
.Nm
checks the counter value, detects out-of-order packets, and emits
statistics about packet loss each
.Ar statsinterval
number of packets received.
Options:
.Bl -tag -width Ds
.It Fl 4
Listen on IPv4 addresses only.
.It Fl 6
Listen on IPv6 addresses only.
.It Fl c Ar statsinterval
Emit statistics every
.Ar statsinterval
packets received. A lower value will be necessary when there is heavy
packet loss.
.It Fl d Ar delay
Wait
.Ar delay
milliseconds after processing a packet, or instead nanoseconds if
.Fl N
is employed.
.It Fl l
Make stdout line buffered. See
.Xr setbuf 3
for the defaults.
.It Fl M Ar address
Listen on the given multicast
.Ar address
instead of everywhere else.
.It Fl N
Changes
.Fl d
argument units to nanoseconds.
.It Fl P Ar packetsize
Assume data from
.Xr udp-sender 1
is of size
.Ar packetsize .
.It Fl p Ar port
Listen on UDP
.Ar port .
Mandatory.
.El
.Pp
The arguments used should ideally agree with those in
.Xr udp-sender 1
for any given test. Only one 
.Xr udp-sender 1
instance should send to a
.Nm
instance, as multiple senders will confuse the packet counting.
.Sh OUTPUT FORMAT
The statistics are whitespace delimited, and include the timestamp,
packet loss count, packet count, packet loss percentage, and a count of
out-of-order packets for a given
.Ar statsinterval
count of received packets.
.Sh EXIT STATUS
.Nm
will listen until terminated, or abort with an exit status >0 if an error
occurs. SIGINT will cause
.Nm
to emit a final statistics line before exiting.
.Sh EXAMPLES
Collect packets:
.Pp
.Dl $ Ic udp-sink -p 2952 -c 10000 -l \&| tee log
.Pp
and to elsewhere feed it:
.Pp
.Dl $ Ic udp-sender -p 2952 -f localhost
.Pp
There is multicast support, though this has not be tested much and will
likely need additional work and improvements:
.Pp
.Dl $ Ic udp-sink -c 100 -4 -p 1234 -M 224.0.66.66
.Dl $ Ic udp-sink -c 100 -6 -p 1234 -M FF15:0:0:0:0:0:0:101
.Sh SEE ALSO
.Xr iperf3 1 ,
.Xr nmap 1 ,
.Xr udp-sender 1
.Sh AUTHOR
Jeremy Mates
