.Dd January  6 2017
.Dt COINFLIP 1
.nh
.Os
.Sh NAME
.Nm coinflip
.Nd heads or tails?
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
emits
.Qq heads
or
.Qq tails
and sets the
.Sh EXIT STATUS
to be 0 if heads or 1 if tails.
.Sh SEE ALSO
.Xr arc4random 3 ,
.Xr randline 1 ,
.Xr shuffle 1
.Sh AUTHOR
.An Jeremy Mates
