.Dd December 25 2018
.Dt ONEOF 1
.nh
.Os
.Sh NAME
.Nm oneof
.Nd pick random argument and display it
.Sh SYNOPSIS
.Bk -words
.Nm
.Ar arg Op ..
.Ek
.Sh DESCRIPTION
.Nm
picks one of the given arguments at random and displays it.
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr arc4random 3 ,
.Xr coinflip 1 ,
.Xr randline 1 ,
.Xr roll 1 ,
.Xr shuffle 1
.Sh AUTHOR
.An Jeremy Mates
.Sh BUGS
.Nm xom
support is not implemented.
