#!/usr/bin/env perl
#
# Returns random line from input.  perldoc -q 'random line'

END {
  print $line;

  unless ( close(STDOUT) ) {
    warn "error: problem closing STDOUT: $!\n";
    exit 74;
  }
}

rand $. < 1 && ( $line = $_ ) while <>
