#!/usr/bin/perl
#
# Returns random line from input.  perldoc -q 'random line'
#
# The author disclaims all copyrights and releases this script into the
# public domain.

END {
  print $line;

  unless ( close(STDOUT) ) {
    warn "error: problem closing STDOUT: $!\n";
    exit 74;
  }
}

rand $. < 1 && ( $line = $_ ) while <>
