#!/usr/bin/env perl
#
# shuffle - print input data in random order
#
# see also `shuf` if you have that toolset installed

my @input = readline;
die "error: no data supplied to shuffle\n" unless @input;

fisher_yates_shuffle(\@input);
print for @input;

# fisher_yates_shuffle(\@array) - generate a random permutation of
# @array in place
sub fisher_yates_shuffle {
    my $array = shift;
    my $i;
    for ($i = @$array; --$i;) {
        my $j = int rand($i + 1);
        next if $i == $j;
        @$array[ $i, $j ] = @$array[ $j, $i ];
    }
}
