#!/usr/bin/perl -w
#
# $Id$
#
# Copyright (c) 2001, Jeremy A. Mates.  This script is free software;
# you can redistribute it and/or modify it under the same terms as
# Perl itself.
#
# Run perldoc(1) on this file for additional documentation.
#
######################################################################
#
# REQUIREMENTS

require 5;

use strict;

######################################################################
#
# MODULES

use Carp;			# better error reporting
use Getopt::Std;		# command line option processing

use File::Tail 0.91;		# tail -f on steroids

######################################################################
#
# VARIABLES

my $VERSION;
($VERSION = '$Revision$ ') =~ s/[^0-9.]//g;

my (%opts, @files);

# various File::Tail object preferences.  listen much faster than default
# to emulate tail(1) at expense of more busy wait.
my $maxinterval = 2;
my $interval = 1;
my $adjustafter = 1;
my $tail = 0;
my $reset_tail = -1;

######################################################################
#
# MAIN

# parse command-line options
getopts('h?', \%opts);

help() if exists $opts{'h'} or exists $opts{'?'};

$maxinterval = $opts{'m'} if exists $opts{'m'} and $opts{'m'} =~ /^\d+$/;
$interval =    $opts{'i'} if exists $opts{'i'} and $opts{'i'} =~ /^\d+$/;
$adjustafter = $opts{'a'} if exists $opts{'a'} and $opts{'a'} =~ /^\d+$/;
$tail =        $opts{'t'} if exists $opts{'t'} and $opts{'t'} =~ /^-?\d+$/;
$reset_tail =  $opts{'r'} if exists $opts{'r'} and $opts{'r'} =~ /^-?\d+$/;

# read from STDIN if no args left
chomp(@ARGV = <STDIN>) unless @ARGV;

# and flag the help text if nothing from STDIN
help() unless @ARGV;

for (@ARGV) {
    push @files, File::Tail->new(
				 name=>"$_",
				 maxinterval => $maxinterval,
				 interval => $interval,
				 adjustafter => $adjustafter,
				 tail => $tail,
				 reset_tail => $reset_tail,
				 );
}

my $rin='';
my $nfound;

# don't buffer STDOUT
$| = 1;

while (1) {
    $nfound = File::Tail::select(undef, undef, undef, 60, @files);
    unless ($nfound) {
	my @ints;
	for (@files) {
	    push @ints, $_->interval;
	}
    }
    for (@files) {
	print $_->read unless $_->predict;
    }
}

exit;

######################################################################
#
# SUBROUTINES

# a generic help blarb
sub help {
    print <<"HELP";
Usage: $0 [opts] [file1 file2 .. fileN]

Merges growing files into single stream

Options for version $VERSION:
  -h/-?  Display this message

Run perldoc(1) on this script for additional documentation.

HELP
    exit;
}

######################################################################
#
# DOCUMENTATION

=head1 NAME

eet.pl - merges growing files into single stream

=head1 SYNOPSIS

To follow two log files at the same time:

  $ eet.pl /var/log/messages /var/log/maillog

=head1 DESCRIPTION

=head2 Overview

This script does rougly the opposite of tee(1), reading in from
multiple files and merging them all into STDOUT.

=head2 Normal Usage

  $ eet.pl [options] [file1 file2 .. fileN]

See L<"OPTIONS"> for details on the command line switches supported.

If no files are mentioned on the command line for reading, this script
will look fo them on STDIN.

=head1 OPTIONS

This script currently supports the following command line switches:

=over 4

=item B<-h>, B<-?>

Prints a brief usage note about the script.

=back

=head1 EXAMPLES

Follow several Apache VirtualHost logfiles, and send them off to
colorize.pl (available on http://freshmeat.net):

  $ eet.pl logs/e.com.log logs/e.org.log | colorize.pl

=head1 BUGS

=head2 Reporting Bugs

Newer versions of this script may be available from:

http://www.sial.org/code/perl/

If the bug is in the latest version, send a report to the author.
Patches that fix problems or add new features are welcome.

=head2 Known Issues

No known bugs.

=head1 TODO

Replace default stub POD entries with real documentation.

=head1 SEE ALSO

perl(1)

=head1 AUTHOR

Jeremy A. Mates, http://www.sial.org/contact/

=head1 COPYRIGHT

Copyright (c) 2001, Jeremy A. Mates.  This script is free software;
you can redistribute it and/or modify it under the same terms as Perl
itself.

=head1 HISTORY

Based heavily on the select_demo script from File::Tail by Matija
Grabnar.

=head1 VERSION

  $Id$

=cut
