CFLAGS=-std=c99 -O3 -Wall -pedantic -fno-diagnostics-color -fstack-protector-all -fPIC -fPIE -pie -pipe

miditimer: miditimer.c
pedaltime: pedaltime.c
pianoteq: pianoteq.c

clean:
	git clean --force -x

.PHONY: clean
