.Dd November 22 2017
.Dt MIDIUTIL 1
.nh
.Os
.Sh NAME
.Nm midiutil
.Nd various MIDI related routines
.Sh SYNOPSIS
.Bk -words
.Nm
.Ar action
.Op Ar args ..
.Ek
.Sh DESCRIPTION
.Nm
offers various handlers to view, filter, or mangle MIDI with. See the
source code for details.
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr lilypond 1 ,
.Xr playit 1 ,
.Xr tlymidity 1
.Sh AUTHOR
.An Jeremy Mates
