#!/bin/sh
#
# Wrapper to preview and play lilypond music,

set -e

LYFILE=`glf --exclude='[.](?!ly$)' '\.ly$' .`

if [ -z "$LYFILE" ]; then
    echo >&2 "no *.ly found (or glf problem)"
    exit 1
fi

ROOTNAME=`fdsplit root "$LYFILE"`
PDF="$ROOTNAME.pdf"

if command test ! -e "$PDF" -o "$LYFILE" -nt "$PDF"; then
    lilypond --silent -dno-point-and-click "$LYFILE"
    mopen "$PDF"
fi

set +e

is-mute -q
if [ $? -eq 1 ]; then
    tlymidity "$ROOTNAME.midi"
fi
