.Dd November 22 2017
.Dt TLYMIDITY 1
.nh
.Os
.Sh NAME
.Nm tlymidity
.Nd wrapper for timidity with lilypond magic
.Sh SYNOPSIS
.Bk -words
.Nm
.Op Ar midi-file
.Ek
.Sh DESCRIPTION
.Nm
passes the given
.Ar midi-file
to
.Xr timidity 1 ,
or lacking one, searches for the most recently modified
.Pa *.midi
file in the current working directory and passes that.
.Pp
If a corresponding
.Pa *.ly
file is found, the first
.Qq % timidity ...
line in the comment header is searched for, and options listed there
added to the command line arguments for
.Xr timidity 1 .
.Pp
Likewise, if a
.Qq % midiutil ...
line is present in the comment header of the
.Pa *.ly
file, the resulting MIDI file is filtered via
.Xr midituil 1 .
Only 
.Xr midituil 1
methods that filter the input MIDI make sense (in particular,
.Cm fuzz
and
.Cm nixcc Ns ).
.Sh EXIT STATUS
.Nm
replaces itself with
.Xr timidity 1
if all goes well, though will exit with a non-zero code if anything goes
awry prior to that.
.Sh EXAMPLES
Sample 
.Cm % timidity
lines to place in the corresponding lilypond file. Only the first such
matching line will be considered.
.Pp
.Dl % timidity --config-file=foo.cfg
.Dl \eversion \&"2.18.2\&"
.Dl ...
.Pp
Where the
.Pa foo.cfg
might contain
.Pp
.Dl soundfont /usr/local/share/timidity/inst/jeux_d_orgues2.sf2
.Pp
To temporarily disable the entry, comment it out via
.Pp
.Dl %% timidity ...
.Pp
Use the
.Fl x
flag to pass arbitrary configuration strings to
.Xr timidity 1 .
.Sh SEE ALSO
.Xr lilypond 1 ,
.Xr midiutil 1 ,
.Xr playit 1 ,
.Xr timidity 1
.Sh AUTHOR
.An Jeremy Mates
