#!/usr/bin/env zsh

for file in "$@"; do
  basename=$file:r
  normed=`mktemp` || exit 1
  sox --norm $file -b 16 -t wav $normed rate 44100 dither -s
  ffmpeg -f wav -i $normed $basename.mp3
  rm $normed
done
