#!/usr/bin/env perl
#
# repeat - something like the ZSH reserved word

$repeat = shift;

if (   !defined $repeat
    or !@ARGV
    or $repeat !~ m/^[0-9]+$/) {
    warn "Usage: repeat count cmd [args ..]\n";
    exit 64;
}

while ($repeat--) {
    $ENV{N} = ++$n;
    system(@ARGV) == 0 or die "could not exec @ARGV: $?\n";
}
