#!/usr/bin/perl
#
# $Id$
# By Jeremy Mates <mailto:jmates@sial.org>
#
# Parses procmail logfiles.
# 
# For documentation, use the -h option or run perldoc on this script.
#
# Distributed under the Artistic License:
# http://www.sial.org/artistic_license.txt
#
######################################################################
#
# MODULES

use Carp;
use Getopt::Std;

use strict;
use vars qw:$VERSION:;

######################################################################
#
# CONSTANTS

my (%opts, $procmailrc, $logfile);

# where to look for the procmailrc...
$procmailrc = $ENV{'HOME'} . '/.procmailrc';

($VERSION = '$Revision$ ') =~ s/[^0-9.]//g;

######################################################################
#
# MAIN

# parse command-line options
getopts('h?', \%opts);

help() if exists($opts{'h'}) || exists($opts{'?'});

# first, we find out where the logfile is
open (FILE, $procmailrc) or die "Error opening $procmailrc: $!\n";
while (<FILE>) {
    chomp;
    # not too sure about formatting allowed in .procmailrc...
    if (m/LOGFILE\s*=\s*(.*)$/) {
	my $logfile_loc = $1;
	# convert (potentially) shell-notational logfile loc
	# to a full pathname (e.g. $HOME/.pm_log -> /home/user/.pm_log)
	$logfile = `echo $logfile_loc`;
    }
}
close (FILE);

# parse procmail's logfile

######################################################################
#
# SUBROUTINES

# a generic help blarb
sub help {
    print <<"HELP";
$0 v.$VERSION
Usage: $0 [options]
Purpose: procmail logfile parser.

Options:
  -h/-?  Display this message

Run perldoc on this script for more documentation.

HELP
    exit;
}

__END__

=head1 NAME

fm.pl - procmail logfile parser.

=head1 SYNOPSIS

Pretty simple, just run:

  $ fm.pl

=head1 DESCRIPTION

fm.pl is a simple procmail logfile parser good for giving you summary
reports about what procmail has been doing with your email.

Ideally, it should be run daily from cron to keep you informed of
where your recent mail has gone, especially if you have folders that
you do not check on a regular basis but might be interested if mail
goes to them.

=head1 USAGE

Typically...

  $ fm.pl

=head1 OPTIONS

None at the moment.

=heal1 LICENSE

This script is distributed under the terms of the Artistic License:
http://www.sial.org/artistic_license.txt

=head1 BUGS

Lots, probably.

=head1 SEE ALSO

cron(1), perl(1), procmail(1), procmailrc(5)

=head1 AUTHOR

Jeremy A. Mates, jmates@sial.org

=cut
