#!/usr/bin/env perl
#
# bigterm - launches a big (or sometimes small) terminal. must agree
# with ~/.Xdefaults (see dotfiles repo)

use feature qw(say);

@bigterms = qw(cous excel mf spleen tt wr);
@shell    = qw(/bin/ksh -l);

if (@ARGV) {
    if ( grep { $ARGV[0] eq $_ } @bigterms ) {
        delete $ENV{TMUX};
        exec( 'solitary', $ENV{HOME},
            qw(xterm -tn xterm-256color +cm +dc +itc -class),
            "$ARGV[0]term", '-e', @shell )
          or die "exec failed: $!\n";
    }
}

say join ' ', @bigterms;
