.Dd January  1 2018
.Dt NOCOLOR 1
.nh
.Os
.Sh NAME
.Nm nocolor
.Nd removes color codes from standard out and error streams
.Sh SYNOPSIS
.Bk -words
.Nm
.Ar command
.Op Ar arg ..
.Ek
.Sh DESCRIPTION
.Nm
removes color codes from the standard output and error streams of the
given
.Ar command .
Output buffering is disabled by default. However, input is read by line
so
.Nm
does not suit interactive utilities.
.Pp
The need for this script can be obviated via the
.Xr xterm 1
resource
.Cm colorMode
in
.Pa ~/.Xdefaults
.Pp
.Dl XTerm*colorMode:false
.Pp
though--alas!--not all terminal software is so enlightened.
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr xterm 1 ,
\fIXterm Control Sequences\fP
.Sh AUTHOR
.An Jeremy Mates
.Sh CAVEATS
Interactive utilities are a problem on account of the line-based input
reads done by
.Nm .
Correcting this would require smaller input reads and manual buffer
wrangling instead of relying on
.Xr getline 3 .
.Pp
.Nm
uses threaded I/O so may emit data differently than asynchronous I/O
does.
.Pp
.Nm
is new code and may have edge cases not yet discovered.
.Pp
.Nm
is not for those who enjoy the double-ended digestive distress of a
unicorn splattered all over their terminals.
