.Dd August 11 2018
.Dt NOCOLOR 1
.nh
.Os
.Sh NAME
.Nm nocolor
.Nd removes color codes from standard out and error streams
.Sh SYNOPSIS
.Bk -words
.Nm
.Ar command
.Op Ar arg ..
.Ek
.Sh DESCRIPTION
.Nm
removes (some) color codes from the standard output and error streams
of the given
.Ar command .
The need for this script can be obviated via the
.Xr xterm 1
resource
.Cm colorMode
in
.Pa ~/.Xdefaults
.Pp
.Dl XTerm*colorMode:false
.Pp
though--alas!--not all terminal software is so enlightened.
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr xterm 1 ,
\fIXterm Control Sequences\fP
.Sh AUTHOR
.An Jeremy Mates
.Sh CAVEATS
.Nm
uses threaded I/O so may emit data differently than asynchronous I/O
does, though assuming a particular relationship between when output
appears from different streams is likely an error.
.Pp
This code has various edge cases and omissions; these in turn depend on
the terminal software involved and what that parses. A much better place
to solve this would be in a terminal or library that supports such.
.Pp
.Nm
is not for those who enjoy the double-ended digestive distress of a
unicorn splattered all over their terminals.
