#!/usr/local/bin/sh
#
# nukes the (horrid) 'alternate screen' feature such that documentation
# in the man page does not vanish after the man page viewer is exited

set -e

TF=`mktemp`

infocmp \
| sed -e 's/[sr]mcup=[^,]*,//' \
> "$TF"

tic -o ~/.terminfo/ -- "$TF"
rm -- "$TF"
