#!/usr/bin/env perl
#
# Break out escape codes to see what control sequences are being used e.g.
# by roguelikes.
while (readline) {
    s/\e/\n\\e/g;    # ESC
    s/\a/\\a/g;      # BEL (used by set-term-title things)
    print;
}
# possibly more efficient but might be tricky depending on shell getting
# ESC to tr properly: (also tr doesn't read a file or stdin so....)
#tr $'\e' '\n' < $1
