#!/usr/local/bin/sh
QUIET=0
OPT=
while getopts q OPT; do
   case "$OPT" in
      q) QUIET=1 ;;
   esac
done
osascript -e 'get volume settings' \
| egrep -q '(^output volume:0,|output muted:true)'
if [ "$?" -eq 0 ]; then
   [ "$QUIET" -eq 0 ] && echo mute
   exit 0
fi
exit 1
