#!/bin/sh
#
# Create a MX record.
#
#   create-host mailhost 192.0.2.25
#   create-mx mailhost mailhost.example.net
#
# NOTE that some DNS servers (and moreover certain Mail Transport
# Agents) are rather picky about what MX point to, e.g. if a CNAME is
# improperly made the target of a MX record.
#
# This script requires that some other record exists for both the host
# the MX is being added for, e.g. an A record, and that the MX target
# has some sort of record for it. `create-host` can be used to satisfy
# these requirements.

DOM=example.net
KEY=/etc/nsuk.key
DNS_TTL=3593

# e.g. for testing, or if running local to the master DNS server anyways;
# otherwise perhaps better to let nsupdate figure out where the request
# needs to go.
SERVER=127.0.0.1

MAXWAITSECS=7
PROG_NAME=`basename $0`

[ $# -ne 2 -a $# -ne 3 ] && {
  echo >&2 "Usage: $PROG_NAME host mxhost.dom [priority]"
  exit 64
}

echo $1 | fgrep $DOM >/dev/null && {
  echo >&2 "$PROG_NAME: use short host name"
  exit 65
}

PRIORITY=0
[ $# -eq 3 ] && PRIORITY=$3

(
  if [ ! -z $SERVER ]; then
    echo server $SERVER
  fi
  cat <<EOF
prereq yxdomain $1.$DOM.
prereq yxdomain $2.
update add $1.$DOM. $DNS_TTL MX $PRIORITY $2.
send
EOF
) | nsupdate -k $KEY -t $MAXWAITSECS

STATUS=$?
if [ $STATUS -ne 0 ]; then
  echo "$PROG_NAME: failed to update add $1.$DOM. $DNS_TTL MX $PRIORITY $2."
fi
exit $STATUS
