#!/bin/sh
#
# Creates a PTR, though accepts it in the form of "host ipaddr" and then
# figures out the IPv4 in-addr foo.

DOM=example.edu
KEY=/etc/nsuk.key
MAXWAITSECS=7

[ $# -ne 2 ] && {
  echo >&2 "usage: $0 host ipaddr"
  exit 64
}

echo $1 | grep $DOM && {
  echo >&2 "$0: use short host names"
  exit 65
}

[ -r $KEY ] || {
  echo >&2 "$0: cannot read nsupdate keyfile $KEY"
  exit 65
}

REV=`perl -e 'print join ".", reverse split /[.]/, shift' $2`

nsupdate -k $KEY -t $MAXWAITSECS <<EOF
prereq nxrrset $REV.in-addr.arpa. PTR
update add $REV.in-addr.arpa 86400 PTR $1.$DOM.
send
EOF

STATUS=$?
if [ $STATUS -ne 0 ]; then
  echo >&2 "$0: could not update PTR"
fi

exit $STATUS
