#!/bin/sh
#
# Create A host (and PTR if possible). (Reverse ownership might be tricky
# to figure out, or cross ownership boundaries...)

DOM=example.edu
KEY=/etc/nsuk.key
MAXWAITSECS=7

[ $# -ne 2 ] && {
  echo >&2 "usage: $0 host ipaddr"
  exit 64
}

echo $1 | grep $DOM && {
  echo >&2 "$0: use short host names"
  exit 65
}

[ -r $KEY ] || {
  echo >&2 "$0: cannot read nsupdate keyfile $KEY"
  exit 65
}

nsupdate -k $KEY -t $MAXWAITSECS <<EOF
prereq nxrrset $1.$DOM A
update add $1.$DOM 86400 A $2
send
EOF

STATUS=$?
if [ $STATUS -ne 0 ]; then
  echo >&2 "$0: non-zero exit from nsupdate (A not created)"
else
  REV=`perl -e 'print join ".", reverse split /[.]/, shift' $2`

  nsupdate -k $KEY -t $MAXWAITSECS <<EOF_REV
prereq nxrrset $REV.in-addr.arpa. PTR
update add $REV.in-addr.arpa 86400 PTR $1.$DOM.
send
EOF_REV

  STATUS=$?
  if [ $STATUS -ne 0 ]; then
    echo >&2 "$0: non-zero exit from nsupdate (PTR not created)"
  fi
fi

exit $STATUS
