#!/bin/sh
#
# Delete a CNAME.
#
#   delete-cname pointertoblah

DOM=example.net
KEY=/etc/nsuk.key

# e.g. for testing, or if running local to the master DNS server anyways;
# otherwise perhaps better to let nsupdate figure out where the request
# needs to go.
SERVER=127.0.0.1

MAXWAITSECS=7
PROG_NAME="`basename "$0"`"

[ "$#" -ne 1 ] && {
  echo >&2 "usage: $PROG_NAME cname"
  exit 64
}

echo "$1" | fgrep "$DOM" >/dev/null && {
  echo >&2 "$PROG_NAME: use short host name"
  exit 65
}

[ -r "$KEY" ] || {
  echo >&2 "$PROG_NAME: cannot read nsupdate keyfile $KEY"
  exit 65
}

(
  if [ ! -z "$SERVER" ]; then
    echo "server $SERVER"
  fi
  cat <<EOF
prereq yxrrset $1.$DOM. CNAME
update delete $1.$DOM. CNAME
send
EOF
) | nsupdate -k "$KEY" -t "$MAXWAITSECS"

STATUS=$?
if [ "$STATUS" -ne 0 ]; then
  echo "$PROG_NAME: failed to update delete $1.$DOM. CNAME"
fi
exit "$STATUS"
