#!/bin/sh
#
# Deletes PTR for a given ip address.

DOM=example.edu
KEY=/etc/nsuk.key
MAXWAITSECS=7

[ $# -ne 1 ] && {
  echo >&2 "usage: $0 ipaddr"
  exit 64
}

[ -r $KEY ] || {
  echo >&2 "$0: cannot read nsupdate keyfile $KEY"
  exit 65
}

REV=`perl -e 'print join ".", reverse split /[.]/, shift' $1`

nsupdate -v -d -k $KEY -t $MAXWAITSECS <<EOF
prereq yxrrset $REV.in-addr.arpa. PTR
update delete $REV.in-addr.arpa. PTR
send
EOF

STATUS=$?
if [ $STATUS -ne 0 ]; then
  echo >&2 "$0: non-zero exit from nsupdate"
fi

exit $STATUS
