#!/bin/sh
#
# Delete an arbitrary DNS record.
#
#   create-record _VLMCS._tcp IN SRV 0 100 1688 mskms.example.net
#   delete-record _VLMCS._tcp IN SRV 0 100 1688 mskms.example.net

DOM=example.net
KEY=/etc/nsuk.key

# e.g. for testing, or if running local to the master DNS server anyways;
# otherwise perhaps better to let nsupdate figure out where the request
# needs to go.
SERVER=127.0.0.1

MAXWAITSECS=7
PROG_NAME=`basename $0`

[ $# -eq 0 ] && {
  echo >&2 "usage: $PROG_NAME host x [y z]"
  exit 64
}

HOST=$1
shift

echo $HOST | fgrep $DOM >/dev/null && {
  echo >&2 "$PROG_NAME: use short host name"
  exit 65
}

[ -r $KEY ] || {
  echo >&2 "$PROG_NAME: cannot read nsupdate keyfile $KEY"
  exit 65
}

(
  if [ ! -z $SERVER ]; then
    echo server $SERVER
  fi
  cat <<EOF
update delete $HOST.$DOM. $@
send
EOF
) | nsupdate -k $KEY -t $MAXWAITSECS

STATUS=$?
if [ $STATUS -ne 0 ]; then
  echo "$PROG_NAME: failed to update delete $HOST.$DOM. $@"
fi
exit $STATUS
