#!/bin/sh
#
# Deletes PTR for a given ip address. The correct reverse form will
# be calculated by the code, so do not use the in-addr.arpa or
# ip6.arpa form.
#
#   create-host blah 192.0.2.42 2001:db8::c000:22a
#   delete-ptr 192.0.2.42
#   delete-ptr 2001:db8::c000:22a

DOM=example.net
KEY=/etc/nsuk.key

# e.g. for testing, or if running local to the master DNS server anyways;
# otherwise perhaps better to let nsupdate figure out where the request
# needs to go.
SERVER=127.0.0.1

MAXWAITSECS=7
PROG_NAME=`basename $0`

[ $# -ne 1 ] && {
  echo >&2 "usage: $PROG_NAME ipaddr"
  exit 64
}

[ -r $KEY ] || {
  echo >&2 "$PROG_NAME: cannot read nsupdate keyfile $KEY"
  exit 65
}

REV=`v4addr -q -r $1`
if [ -z $REV ]; then
  REV=`v6addr -q -r $1`
  if [ -z $REV ]; then
    echo >&2 "$PROG_NAME: could not parse v4 or v6 address from $1"
    exit 65
  fi
fi

(
  if [ ! -z $SERVER ]; then
    echo server $SERVER
  fi
  cat <<EOF
prereq yxrrset $REV PTR
update delete $REV PTR
send
EOF
) | nsupdate -k $KEY -t $MAXWAITSECS

STATUS=$?
if [ $STATUS -ne 0 ]; then
  echo "$PROG_NAME: failed to delete $REV PTR"
fi
exit $STATUS
