#!/bin/sh
#
# Somewhat smart "diff" utility, does CVS, Subversion, or git diff if
# this seems relevant (by various file tests), or attempts regular diff
# if possible.
#
# The author disclaims all copyrights and releases this script into
# the public domain.

PROG_NAME=`basename $0`

# First, attempt version control diff...
[ -f CVS/Root ] && exec cvs diff $@
[ -d .svn ] && exec svn diff $@
findup -q .git
STATUS=$?
if [ $STATUS -eq 0 ]; then
  git diff --quiet --exit-code
  STATUS=$?
  if [ $STATUS -eq 1 ]; then
    exec git diff $@
  else
    exit $STATUS
  fi
fi

# Otherwise, hunt for diffs based on various conventions I use
if [ $# -eq 0 ]; then
  echo "Usage: `basename $0` [file1 file2 .. fileN]" >&2
  exit 1
else
  for input in "$@"; do
    if [ ! -f "$input" ]; then
      echo "$PROG_NAME: skipping non-file: $input" >&2
      continue
    fi
    # *.orig and *.old common conventions I use for quick edits, *.orig
    # for the orig command (probably should use git for such quick edits
    # instead?)
    for backup_suffix in .orig .old; do
      if [ -f "$input$backup_suffix" ]; then
        diff "$input$backup_suffix" "$input"
        break
      fi
    done
  done
fi
