#!/bin/sh
#
# $Id$
#
# The author disclaims all copyrights and releases this script into
# the public domain.
#
# Somewhat smart "diff" utility, does CVS, Subversion, or git diff if
# this seems relevant (by various file tests), or attempts regular diff
# if possible.

# should be 0, if errors will be that of last error to occur
RETURN=0

if [ -d CVS -a -f CVS/Root ]; then
  exec cvs diff $@
fi

if [ -d .svn ]; then
  exec svn diff $@
fi

if [ -d .git ]; then
  exec git diff $@
fi

if [ $# -eq 0 ]; then
  echo "Usage: `basename $0` file1 [file2 .. fileN]"
  exit 1
else
  # *.orig and *.old common conventions I use for quick edits, *.orig
  # for the orig command (probably should use git for such quick edits
  # instead?)
  for file in "$@"; do
    if [ -f $file.orig ]; then
      diff $file.orig $file
    elif [ -f $file.old ]; then
      diff $file.old $file
    fi
  done
fi
