.Dd November 21 2017
.Dt NODUPENV 1
.nh
.Os
.Sh NAME
.Nm nodupenv
.Nd strip duplicate environment variables
.Sh SYNOPSIS
.Nm nodupenv
.Bk -words
.Ar command
.Op Ar args ..
.Ek
.Sh DESCRIPTION
.Nm
strips duplicate environment variables; only the first instance of a
duplicate is passed on to the subsequent
.Ar command .
This agrees with how certain programs handle duplicate environment values
(Go, Perl,
.Cm sudo )
and notably not how
.Cm bash
handles duplicates.
.Pp
.Nm
is not necessary if
.Ar command
strips duplicates; whether and how this is done is up to each individual
.Ar command .
.Cm sudo
was for example patched in late 2015 to keep only the first instance.
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
.Dl $ Ic dupenv FOO=bar FOO=zot env \&| grep FOO
.Dl FOO=bar
.Dl FOO=zot
.Dl $ Ic dupenv FOO=bar FOO=zot nodupenv env \&| grep FOO
.Dl FOO=bar
.Dl $
.Sh SEE ALSO
.Xr dupenv 1 ,
.Xr environ 7 ,
.Xr execve 2
.Pp
There can be security problems when duplicate environment variables are
allowed, especially given that some programs use the first duplicate,
and others the last, and others helpfully pass duplicates along.
.Pp
.Bl -tag -width Ds
.It https://rt.perl.org/Public/Bug/Display.html?id=127158
.It https://www.sudo.ws/repos/sudo/rev/d4dfb05db5d7
.El
.Pp
Perhaps something should be done at the libc level about this?
.Pp
.Bl -tag -width Ds
.It https://sourceware.org/bugzilla/show_bug.cgi?id=19749
.El
.Sh AUTHOR
.An Jeremy Mates
