#!/bin/sh
#
# Return remainder of a given input number, broken down into two or
# more values.
#
# Usage: modulo what-to-modulo-by value-to-modulo
#
#   $ modulo 2 1   
#   1
#   $ modulo 2 2
#   0
#   $ modulo 2 3
#   1
#
# This can also be used for hostnames that contain numbers:
#
#   $ modulo 2 node001
#   1

if [ -z "$1" ]; then
  echo "Usage: `basename $0` what-to-modulo-by value-to-modulo" >&2
  exit 64
fi

# read modulus to use
MODULUS=`echo "$1" | tr -dc 0123456789`
if [ -z "$MODULUS" -o "$MODULUS" -lt 2 ]; then
  MODULUS=2
fi

# then number to apply modulus to: make up number if unset
NUMBER=`echo "$2" | tr -dc 0123456789`
if [ -z "$NUMBER" ]; then
  NUMBER=$RANDOM

  if [ -z "$NUMBER" ]; then
    NUMBER=$$
  fi
fi

exec expr $NUMBER % $MODULUS
