#!/usr/bin/perl
#
# $Id$
#
# The author disclaims all copyrights and releases this script into the
# public domain.
#
# Returns random line from input.  perldoc -q 'random line'

END { print $line }
rand $. < 1 && ($line = $_) while <>
