#!/usr/bin/perl
#
# Wrapper for the Text::Autoformat Perl module. Can be called via a vi
# .exrc entry such as:
#
# map T !Gautoformat
#
# Or vim 6.3+ .vimrc entry:
#
# map T :keepmark .,$!autoformat
#
# And then Text::Autoformat options added there after if needed, such as
# 'right=>72' or similar.
#
# http://sial.org/howto/perl/reformat/
#
# The author disclaims all copyrights and releases this script into the
# public domain.

use Text::Autoformat;

# these are the default preferences
$default = { squeeze => 1, all => 0 };

# merge in user prefs from command line
$input = '$user = {' . $ARGV[0] . '};';
eval $input;
%$user = () if $@;

$options = { %$default, %$user };

$out = autoformat $options;

# KLUGE standardize trailing newline behaviour
chomp $out;

print $out;
