#!/usr/bin/perl
#
# $Id$
#
# The author disclaims all copyrights and releases this script into the
# public domain.
#
# Wrapper for Text::Autoformat. Can be called via a vi .exrc entry
# such as:
#
# map f !Gautoformat
#
# And then Text::Autoformat options added there after if needed, such as
# 'right=>72' or similar.

use Text::Autoformat;

# these are the default preferences
$default = {squeeze=>1,all=>0};

# merge in user prefs from command line
$input = '$user = {'.$ARGV[0].'};';
eval $input;
%$user = () if $@;

$options = { %$default, %$user };

$out = autoformat $options;

# KLUGE standardize trailing newline behaviour
chomp $out;

print $out;
