#!/usr/bin/perl -w
#
# $Id$
#
# Copyright (c) 2002, Jeremy A. Mates.  This script is free software;
# you can redistribute it and/or modify it under the same terms as
# Perl itself.
#
# Run perldoc(1) on this file for additional documentation.
#
######################################################################
#
# REQUIREMENTS

require 5;

use strict;

######################################################################
#
# MODULES

use Carp;         # better error reporting
use Getopt::Std;  # command line option processing

######################################################################
#
# VARIABLES

my $VERSION;
($VERSION = '$Revision$ ') =~ s/[^0-9.]//g;

my @facility = qw(
auth
authpriv
cron
daemon
ftp
kern
lpr
mail
news
security
syslog
user
uucp
local0
local1
local2
local3
local4
local5
local6
local7
);

my @level = qw(
emerg
alert
crit
err
warning
notice
info
debug
);

######################################################################
#
# MAIN

for my $l (@level) {
  for my $f (@facility) {
    system 'logger', @ARGV, '-p', "$f.$l", "yakking to $f.$l";
  }
}

exit;

######################################################################
#
# SUBROUTINES

# a generic help blarb
sub help {
  print <<"HELP";
Usage: $0

Tests what levels/facilities are handled by syslog.

Options for version $VERSION:
  -h/-?  Display this message

Run perldoc(1) on this script for additional documentation.

HELP
  exit;
}

######################################################################
#
# DOCUMENTATION

=head1 NAME

syslog-yakker.pl - tests what levels/facilities are handled by syslog

=head1 SYNOPSIS

  $ syslog-yakker.pl

=head1 DESCRIPTION

=head2 Overview

Tests what levels/facilities are handled by syslog.

=head2 Normal Usage

  $ syslog-yakker.pl

Any command line arguments are passed to logger(1).  The script
attempts to set the B<-p> I<priority> option to logger(1) internally.

=head1 EXAMPLES

None yet.

=head1 BUGS

=head2 Reporting Bugs

Newer versions of this script may be available from:

http://www.sial.org/code/perl/

If the bug is in the latest version, send a report to the author.
Patches that fix problems or add new features are welcome.

=head2 Known Issues

No known bugs.

=head1 SEE ALSO

perl(1)

=head1 AUTHOR

Jeremy A. Mates, http://www.sial.org/contact/

=head1 COPYRIGHT

Copyright (c) 2002, Jeremy A. Mates.  This script is free software;
you can redistribute it and/or modify it under the same terms as Perl
itself.

=head1 VERSION

  $Id$

=cut
